### ISSUE TITLE
Bridge auto angle: FAIL

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#565] opened 2020-10-13 18:43 UTC
### Version
2.2.54 (night build)

### Operating system type + version
Windows

### Behavior
the automatic angles are wrong

#### Project File (.3MF) where problem occurs
[Bridging_Test.zip.amf.zip](https://github.com/supermerill/SuperSlicer/files/5373419/Bridging_Test.zip.amf.zip)

**Comment by Zulaner** [comment] 2020-10-13 18:49
![image](https://user-images.githubusercontent.com/38788588/95902702-0e83ca80-0d8d-11eb-803c-6ef258b03071.png)

**Comment by neophyl** [comment] 2020-10-13 20:13
Actually the one on the right would be my preferred printing angle for the bridge as it’s the shortest distance. The ok one looks very long so that will droop a lot.

**Comment by Zulaner** [comment] 2020-10-13 20:29
the perimeters being detected as overhang, these should not be considered for calculating the bridge distance

**Comment by supermerill** [comment] 2020-10-13 21:16
Currently, the brute-force algorithm check every 2° angle, so it's easy to not be optimal if the optimal angle isn't a multiple of 2.

also duplicate of #234 #149

It's something to revamp...

**Comment by girrrrrrr2** [comment] 2020-10-15 04:10
> Maybe i could publish the hidden setting in the meantime?

That would probably an easy temporary fix. Maybe have a screen somewhere that has a bunch of settings like this, with the request to reach out if you find a good parameter, or something.

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate, enhancement
