### ISSUE TITLE
Settings search does not work properly

### ISSUE THREAD

**Issue by bassamanator** [supermerill/SuperSlicer#2682] opened 2022-04-11 14:24 UTC
### What happened?

The search is mostly broken. I thought I was doing something wrong so I tested it in PrusaSlicer, but the search works there.

![image](https://user-images.githubusercontent.com/61985779/162759901-bea1dc30-b45b-4da4-a8bc-4af66a886408.png)

### Project file & How to reproduce

1. Go to any settings page.
2. Search for 'spiral'
3. Spiral vase setting will not be found

Expected behaviour:
-Spiral vase setting should show up at the top of the search results.

![image](https://user-images.githubusercontent.com/61985779/162760531-221234e1-0fd4-408e-9875-e9f5769b9c78.png)

### Version

Version 2.3.57 SuperSlicer-ubuntu_18.04-gtk2-2.3.57.12.AppImage

### Operating system

> Operating System: Manjaro Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.15.28-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

### Printer model

Voron 0.1 with mini-sherpa; default profile mixed with Ellis profile.

**Comment by supermerill** [comment] 2022-04-11 14:28
can't reproduce on windows.
maybe duplicate of #2672

**Comment by bassamanator** [comment] 2022-04-11 14:32
>if you click on the first entry, where do you go?

Oh it actually takes me to the *expected* results, that is, searching for 'spiral', shows incorrect results, however, the first entry leads me to 'Spiral vase' entry.

**Comment by supermerill** [comment] 2022-04-11 14:38
so it's really a duplicate of 2672, as it seems to have a refresh issue on gtk2

**Comment by bassamanator** [comment] 2022-04-11 14:44
Don't know much about gui toolkits but I just tried [SuperSlicer-ubuntu_18.04-2.3.57.12.AppImage](https://github.com/supermerill/SuperSlicer/releases/download/2.3.57.12/SuperSlicer-ubuntu_18.04-2.3.57.12.AppImage) and it was the same problem there.

**Closed** 2024-08-27 20:00 UTC
Labels: duplicate, ubuntu
