### ISSUE TITLE
fill_aligned_z makes sparsely bridge

### ISSUE THREAD

**Issue by shengyan** [supermerill/SuperSlicer#4240] opened 2024-05-02 07:43 UTC
### What happened?

It seems the new feature ''fill_aligned_z'' in version 2.5.59.9 is making bridge lines sparse in both normal and internal bridges. maybe it should be applied to sparse infill only or turn-off by default.

### Project file & How to reproduce

![fill_aligned_z on](https://github.com/supermerill/SuperSlicer/assets/5512484/cca889a1-4452-4429-9e8a-f1924aad94fc)
![fill_aligned_z off](https://github.com/supermerill/SuperSlicer/assets/5512484/27d38eae-a239-4f87-9242-ea13935942de)

### Version

2.5.59.9

**Comment by supermerill** [comment] 2024-05-03 12:27
can't reproduce, can you send here your project file?

**Comment by shengyan** [comment] 2024-05-04 07:59
It has something to do with "infill extrusion width". Set "infill spacing" to 0.7 for a 0.4mm nozzle, the difference should be visible.
the following project file is based on built-in "0.2mm 0.4nozzle V0" profile, the only change is set "infill spacing" to 0.7mm.
[bug report sample.zip](https://github.com/supermerill/SuperSlicer/files/15208418/bug.report.sample.zip)

**Comment by supermerill** [comment] 2024-05-15 14:18
understood what's going on.
I removed the bridges from the effect of this settings.
Fixed in next nightly & release.

**Closed** 2024-06-05 08:34 UTC
Labels: could not reproduce, fix is live in the last release
