### ISSUE TITLE
Negative estimated print time

### ISSUE THREAD

**Issue by 7s3** [supermerill/SuperSlicer#437] opened 2020-08-31 20:03 UTC
### Version
2.2.53

### Operating system type + version
Windows 10 Pro 64-bit. Version 2004

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
When I slice STL file, the estimated print time is a large negative number.
Should return hours/minutes/seconds, but instead returns something like: -2147483648s

![superslicer_EWrsfiP18b](https://user-images.githubusercontent.com/4492725/91762619-4989c000-eb8a-11ea-9814-84b7261775b8.png)

#### Project File (.3MF) where problem occurs
[fil_hng.zip](https://github.com/supermerill/SuperSlicer/files/5152401/fil_hng.zip)

**Comment by ManuelMcLure** [comment] 2020-08-31 20:07
I see this as well on occasion (and once yesterday a print said it was going to take over 9600 days). Usually moving the object on the bed, rearranging to the center and slicing again fixes the problem.

**Comment by supermerill** [comment] 2020-08-31 20:43
duplicate of #364

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate
