### ISSUE TITLE
Enhancement Request - Support Settings Calibration

### ISSUE THREAD

**Issue by sg000** [supermerill/SuperSlicer#267] opened 2020-06-04 14:29 UTC
### Version
2.2.51

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
Adimlab Gantry - CR10S

### Behavior
The calibrations routines are awesome. Really low on the priority list probably, but one more that would be great to have available is to tune supports. Those tricky settings for z-offset, pattern spacing, etc.

**Comment by supermerill** [comment] 2020-06-04 15:22
duplicate of # #231

it's something i have to work on.
But as i don't use them often (and never changed a setting on these), i have do make a enormous amount of test to have good calibration procedure, so it may takes a while.

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate, enhancement, working on
