### ISSUE TITLE
Sometimes the speed overview includes the travel move

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4287] opened 2024-05-28 19:37 UTC
I can't define to what it could be related, but sometimes I see that speed overview includes a travel speed and that messes up the whole overview. I can not see nuances of layer speed anymore due to wide spectre of speed range. Sometimes it works fine (without travel speed - as it should be),  but then I change something and travel speed jumps in and I can not get rid of it, so I have to reduce the travel speed to the layer speed to be able to see the speed of layers in colour. 
It happens both in 2.4 and 2.5.
Here's how it looks like:

![image](https://github.com/supermerill/SuperSlicer/assets/98842248/0f90d8e5-5a0f-416c-b966-f8c6eadfc55c)

Layer speed is 30, travel is 200.

**Comment by supermerill** [comment] 2024-05-28 22:30
you can use the "max" field you have, in the bottom of your screenshot, to eliminate high speed.

I'll look into it on why and how.

**Comment by CuredPrusa** [comment] 2024-05-29 07:58
I don't think this works properly either:

![image](https://github.com/supermerill/SuperSlicer/assets/98842248/54ffc10b-896a-42ec-9623-454585a37dc5)

**Comment by supermerill** [comment] 2024-05-29 08:33
can't reproduce, can you share your project, or how to make the travel included in the graph?

**Comment by CuredPrusa** [comment] 2024-05-29 09:02
I can't either  :)
I wonder if this is a cursed project.
Here it is at your disposal, I gave up on trying to understand this speed overview.....
[test.zip](https://github.com/supermerill/SuperSlicer/files/15481736/test.zip)

While your at it, please check  why other marks are shown on display out of turn, for example this travel around seam (red vertical line):

![image](https://github.com/supermerill/SuperSlicer/assets/98842248/537512c3-853a-475f-a053-19e351599ea3)

And try to see how the print goes at layer 1.60mm. Does this look normal on your computer? Maybe it's my computer, idk.

![image](https://github.com/supermerill/SuperSlicer/assets/98842248/925e1866-a047-4cd9-a24e-e8010bc45ebe)

**Comment by supermerill** [comment] 2024-05-29 09:36
ok.
If you have selected "travel" as visible, and then you reslice, then they will be included.

**Comment by CuredPrusa** [comment] 2024-05-29 09:49
>If you have selected "travel" as visible, and then you reslice, then they will be included.

Nice! At least I know now how to get rid of travel speed on display. Thanks! I hope you agree travel speed should by all means not be included  in speed overview.

**Comment by supermerill** [comment] 2024-05-29 13:48
In prusaslicer, it's included is shown.
Currently, I replicate the behaviour.

**Comment by CuredPrusa** [comment] 2024-05-29 13:51
Ok.
What do you say about other two strange things?

**Comment by CuredPrusa** [comment] 2024-05-29 14:36
Ok, as long as you're aware of the quirks, I'm fine with that. 
Thanks.

**Comment by CuredPrusa** [comment] 2024-05-31 11:39
>If you have selected "travel" as visible, and then you reslice, then they will be included.

I wish SS can reslice (Ctrl+R) every time, regardless if there's a change or not.

**Comment by supermerill** [comment] 2024-06-03 07:05
it will in next nightly

**Closed** 2024-06-12 16:46 UTC
Labels: bug, fix is live in the last release

**Comment by CuredPrusa** [comment] 2024-06-13 13:38
In 2.5  .12 still can not reslice unless there's a change.
