### ISSUE TITLE
Coordinate outside allowed range

### ISSUE THREAD

**Issue by guestisp** [supermerill/SuperSlicer#66] opened 2019-05-09 21:44 UTC
### Version
https://github.com/supermerill/Slic3r/commit/6df17e1dd160ff617783058a19c0f1b1e47ef20d

### Operating system type + version
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

### Behavior
Trying to slice the following (only the dog, not the box):
https://www.thingiverse.com/thing:220609
we get:

```
ASSERT INFO:
Slic3r has encountered an error
Coordinate outside allowed range
```

the same model is sliced properly with the upstream slic3r, i've printed it multiple times.

**Comment by uniacke1** [comment] 2019-06-12 12:14
I'm observing this too, local build of sources on linux.

**Comment by uniacke1** [comment] 2019-06-21 01:46
This problem is caused by the "Rectilinear (filled)" solid infill pattern. Changing it, or altering the "anchor solid infill" percentages to (e.g.) 1mm/1mm makes the bug go away.

**Comment by supermerill** [comment] 2019-07-02 08:31
can't reproduce with the last version.
If you can, please link me the project file (.3mf)

**Comment by uniacke1** [comment] 2019-07-02 09:56
Sure, here you go.

[FilamentPM-silver.3mf.gz](https://github.com/supermerill/Slic3r/files/3349445/FilamentPM-silver.3mf.gz)

**Comment by supermerill** [comment] 2019-07-02 13:14
Seems like I have fixed this in my dev build.

**Comment by uniacke1** [comment] 2019-07-02 16:59
Superb, I'll pull and recompile to give it a sniff test. Thanks!

**Comment by uniacke1** [comment] 2019-07-03 12:45
This does indeed appear to have been fixed!

**Comment by VanessaE** [comment] 2021-01-27 12:30
This is not fixed, or perhaps I should say it has resurfaced.  I'm at commit a4699e72fc5afbde8506aea8306ad4b9e9ba9970, newly built just before this comment.  Try this project:

[Benchy_Bernie_1.5x.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5880111/Benchy_Bernie_1.5x.3mf.zip)

The model slices fine at 100% (normal) size, but scale it up some and it throws "Coordinate outside allowed range" as per this issue's title after spending some time slicing.

Setting the anchors to 0/0 to disable them did not help, however, setting the solid infill to "rectilinear" (not "filled") per your suggestion *does* work.

**Comment by jhoblitt** [comment] 2021-02-14 21:11
I'm seeing this as well and I can't seem to escape it by changing the infill type(s).

**Comment by jhoblitt** [comment] 2021-02-14 21:16
The only way I can resolve the error is by scaling the part down to 25% scale. Anything much larger then that fails.  This is really odd as previous versions of the part were slicing OK (STLs generated by f360).  I have tried running an STL repair and reimporting the part from a OBJ with no change in behavior.  This is happening with 2.3.55.2.

**Comment by jhoblitt** [comment] 2021-02-17 03:30
@supermerill This is still happening with the nightly build from ~24 days ago.  PrusaSlicer 2.3.0 is able to slice the files.  I started trying older versions and it works with SS 2.3.55.0 but fails with the same error under 2.3.55.1.

**Comment by tecnopolis-ve** [comment] 2021-03-04 20:35
With superslicer 2.3.55.5 does ocurr the same.

I've figured out how to "alleviate" this issue by changing Anchor solid infill by X mm from rectilinear (filled) to rectilinear.

I've tried with a 3dbenchy (normal size does work, scaling over 200% fails)

I think that this issue must be reopened.

**Comment by TimbreDesign** [comment] 2021-03-05 13:59
I have also now experienced this with 2.3.55.

I have been oddly able to stop the error by flipping the print over (requiring support) and lowering the layer height.

Here is the file:

[filament_tube_fix.zip](https://github.com/supermerill/SuperSlicer/files/6090898/filament_tube_fix.zip)

**Comment by supermerill** [comment] 2021-06-02 14:36
can't reproduce in 2.3.56.1

**Comment by Majestry** [comment] 2021-07-03 10:39
I can reproduce this issue on 2 separate models.
Version 2.3.56.6, MacOs BigSur 11.4 (M1 CPU)
Bed size is set to 235x235x250, model size is 85x134x100. The object was positioned automatically, I didn't moved it on the bed.
If i set infill to 0 - model is sliced, otherwise i got error Coordinate outside allowed range
Github do not allow me to download the m3f file (return the 422 with size is not provided, which is weird), so here is the direct link to 3mf file: https://drive.google.com/file/d/18GI9keV177xMhC34SFBrUKOABO-hvkMV/view?usp=sharing

**Comment by supermerill** [comment] 2021-07-03 17:33
@Majestry 
I loaded your .3mf and it slices perfectly on a fresh 2.3.56.6
can you take a screenshot of what's going on after you load & slice it?

**Comment by Majestry** [comment] 2021-07-03 17:44
@supermerill sure, here is the link to screen record when error occures. https://www.youtube.com/watch?v=WMaPeugcHRo
Also, here i loaded the same model and set infill to 0 - and it was sliced without error. https://youtu.be/oSMP38DvXp8

**Comment by nogginSQZ** [comment] 2021-07-08 22:36
I have same issue with another complicated model: also during "Preparing infill". Sometimes, I can work around the problem by fiddling with Slicing -> Filtering -> Resolution (0.0001 or 0.00001 or 0). But otherwise, I'm stuck.

**Comment by nogginSQZ** [comment] 2021-07-09 13:33
I found out more. It turns out that if I set Perimeters & Shell -> Vertical shells -> Perimeters to 1, then my own model produces the "Coordinate outside allowed range" error.  However, by setting the sparse infill to 0%, the error goes away. I can reproduce this behavior with @Majestry's model from a virgin state:
```tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX); ~/Software/SuperSlicer-ubuntu_18.04-2.3.56.6b.AppImage --datadir ${tmp_dir}; rm -rf ${tmp_dir}```
where I click the configuration menu away and then load `~/Downloads/Nezuko_Kamado.3mf`
This model slices fine unless I set number of perimeters to 1. Hope this helps

**Comment by supermerill** [comment] 2021-07-09 15:28
I'll try on my ubuntu vm.

**Comment by nonchip** [comment] 2021-07-19 10:16
just happened to me too, during "Generating perimeters" on this project:
[cube_hologram.zip](https://github.com/supermerill/SuperSlicer/files/6839973/cube_hologram.zip) (renamed 3mf file to zip to shut github up).
I'm on SuperSlicer_2.3.56.6b (installed from [your release](https://github.com/supermerill/SuperSlicer/releases/tag/2.3.56.6b) via appimage)

**Comment by soupkitchenfilms** [comment] 2021-07-21 12:18
This is happening for me on a M1 Mac with Big Sur on version 2.3.56.7
It seems to be only for very high detailed models. It won't slice this moon model without erroring. https://www.thingiverse.com/thing:3532973

**Comment by supermerill** [comment] 2021-08-23 18:03
@nonchip Can't reproduce on 2.3.56.8 on windows.
@soupkitchenfilms Can't reproduce on a prusa mk3 0.2mm, Can you test again on the 2.3.56.8? there is some fix inside it. If it continue to fail, can you post here the failing project file?

**Comment by RealDeuce** [comment] 2021-08-29 04:42
Occured on FreeBSD build of 2.3.56.8 with thing::4717095 scaled to 250mm in largest dimension, lain on one of the backs or on the lower back and cut flat with cut tool, 10% gyroid infill, filled Solid/Top/Bottom.

**Comment by RealDeuce** [comment] 2021-08-30 10:46
[BearHead-bad.zip](https://github.com/supermerill/SuperSlicer/files/7076119/BearHead-bad.zip)
Failed project file.

**Comment by supermerill** [comment] 2021-08-30 14:31
> Failed project file.

Does it also fails if the slicer is locked on one thread/core ?

success on windows.
will try on linux when i'll have the time.

**Comment by RealDeuce** [comment] 2021-08-31 06:22
Yes, it still fails when pinned to a single core.

**Comment by RealDeuce** [comment] 2021-08-31 07:23
Attached the trace level log.  FWIW, it ends with this:
```
[2021-08-31 02:31:58.184419] [0x0000000806849000] [info]    Discovering vertical shells...
[2021-08-31 02:31:58.184441] [0x0000000806849000] [trace]   discover_horizontal_shells()
[2021-08-31 02:32:50.216428] [0x0000000806849000] [info]    Bridge over infill...
[2021-08-31 02:32:53.981397] [0x0000000806849000] [info]    overextrude over Bridge...
[2021-08-31 02:32:53.981406] [0x0000000806849000] [info]    overextrude over Bridge...
[2021-08-31 02:32:53.981410] [0x0000000806849000] [info]    overextrude over Bridge...
[2021-08-31 02:32:53.981413] [0x0000000806849000] [info]    overextrude over Bridge...
[2021-08-31 02:32:53.981420] [0x0000000806849000] [debug]   Filling layers in parallel - start
```
[slice-log.zip](https://github.com/supermerill/SuperSlicer/files/7081761/slice-log.zip)

Using a normal for() instead of tbb::parallel_for() fails in the same manner.

Printing the values gives me this:
Coordinate outside allowed range... -9223372036854775808, -9223372036854775808 > 4611686018427387903

Which, -9223372036854775808 is 0x8000,0000,0000,0000

And now I'm off to bed. :)

**Comment by supermerill** [comment] 2021-08-31 08:27
can reproduce on linux

**Comment by supermerill** [comment] 2021-09-04 15:57
Found the problem.
Seems like on linux/g++ boost::voronoi can return nan
Also the std::abs on g++ doesn't keep nan and write a big number instead.

**Comment by Belstrekkie** [comment] 2021-11-13 09:53
Both version 2.3.57.4 and 2.3.57.5 are giving me the coordinate outside allowed range in the Windows version, whereas I haven't had any issues in 2.3.57.3 and earlier. In the image the sliced object is version .3 and the error .4. The position and settings are exactly the same.
![image](https://user-images.githubusercontent.com/34160776/141614309-fd0d6dbe-d188-4bc3-897e-d1e2673c71b7.png)

**Comment by alfrix** [comment] 2021-11-13 19:47
i have also found this bug in windows 2.3.57.4 and 2.3.57.5, but not on 2.3.57.3 (same as Belstrekkie)

adding a cube and moving it to the left past 250 mm produces the error
![Captura](https://user-images.githubusercontent.com/1247237/141656788-02667fb0-6302-4c40-8ea5-9a460ff6c7d1.JPG)

[Aspecto-Caja.zip](https://github.com/supermerill/SuperSlicer/files/7532646/Aspecto-Caja.zip)

**Comment by Maximilian-Staab** [comment] 2021-11-14 09:15
I'm getting the same error on 2.3.57.5, but only if "brim" is enabled:
![image](https://user-images.githubusercontent.com/20892091/141674908-5888f9bf-ebb6-4248-a1fa-577354af7b8f.png)

**Comment by Maximilian-Staab** [comment] 2021-11-18 13:20
The nightly build fixed the issue for me, thanks!

**Closed** 2021-12-15 17:51 UTC
Labels: bug, fix is live in the last release

**Comment by Dreistein75** [comment] 2021-12-20 01:02
Sorry, not good with GitHub. I have the newest SuperSlicer (MacOS on ARM) and the following STL from PrusaPrinters gives the Error with the "Coordinate outside allowed range". So guess this is still not fixed entirely.


[white-christmas.stl.zip](https://github.com/supermerill/SuperSlicer/files/7741961/white-christmas.stl.zip)

**Comment by supermerill** [comment] 2021-12-20 03:14
@Dreistein75 
can't reproduce. Maybe post your project file?

**Comment by Dreistein75** [comment] 2021-12-20 13:49
@supermerill 
I just re-tried and the error is still there. I saved the project as 3mf and I will attach it here. It is SuperSlicer 2.3.57.7 for ARM MacOS

[SuperSlicerProblem.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7745737/SuperSlicerProblem.3mf.zip)

**Comment by INeDiA** [comment] 2021-12-21 10:13
> @supermerill I just re-tried and the error is still there. I saved the project as 3mf and I will attach it here. It is SuperSlicer 2.3.57.7 for ARM MacOS
> 
> [SuperSlicerProblem.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7745737/SuperSlicerProblem.3mf.zip)

same here; switched back to the regular release (no ARM) and it works without any issue

**Comment by supermerill** [comment] 2021-12-21 10:16
I think something is creating Nan somewhere when compiled with arm. Next to impossible to fix without a mac mini on hand. Problem is, they are still kind of expensive.

**Comment by yonkiman** [comment] 2021-12-22 21:07
I'm also getting a"Coordinate outside allowed range" error when I try to move the object towards the upper right of the build plate.  If I pull it in closer to the center it slices fine.  I've attached the project file
[Coordinate outside allowed range SS 2.3.57.5, Windows 10.zip](https://github.com/supermerill/SuperSlicer/files/7765231/Coordinate.outside.allowed.range.SS.2.3.57.5.Windows.10.zip)
.

**Comment by supermerill** [comment] 2021-12-22 22:30
@yonkiman on the 2.3.57.5 yes, but it doesn't happen on the latest release (tested on 2.3.57.8)

**Comment by yonkiman** [comment] 2021-12-23 00:28
Apologies - should have made sure I was on the latest version!

**Comment by supermerill** [comment] 2022-07-12 15:46
@elcojacobs no problem for me.
your project?

**Comment by elcojacobs** [comment] 2022-07-13 11:53
This is very strange, I cannot reproduce the error now. It happened on multiple models, even after restart of the appimage.
If it ever happens again, I'll get you a 3mf.

**Comment by elcojacobs** [comment] 2022-07-13 20:37
Seems fixed in yesterdays nightly. Could you reproduce it in the 'better fixes' nightly?
The bug with 2 times the same checkbox label is still there.
