### ISSUE TITLE
Sacrificial layer not bridging properly

### ISSUE THREAD

**Issue by paulrmatei** [supermerill/SuperSlicer#2241] opened 2022-01-18 19:15 UTC
### What happened?

Sacrificial layer isn't bridging properly
Attached a screenshot from superslicer, one from prusaslicer(2.4)
Prusaslicer
![endless-shelf-prusaslicer](https://user-images.githubusercontent.com/53083842/150002173-8b218c7f-6eff-41e4-9e9b-78fc50c4cec9.png)

Superslicer
![endless-shelf-superslicer](https://user-images.githubusercontent.com/53083842/150002197-bbf56c2d-5fe2-4c06-909f-d0963f01bbf2.png)

### Project file & How to reproduce

Import the following file
[connector-v2.zip](https://github.com/supermerill/SuperSlicer/files/7891684/connector-v2.zip)
Set layer height to 0.16 or below
Go to layer ~109 (~11.7mm)

### Version

2.3.57.9

### Operating system

SuperSlicer-ubuntu_18.04-gtk3-2.3.57.8

**Comment by supermerill** [comment] 2022-01-18 19:59
remove "only one peri on top" at least for this layer.
That's something I have to improve, yes.

Duplicate of 1494

**Comment by paulrmatei** [comment] 2022-01-20 10:40
Thank you
That worked

**Closed** 2022-01-20 10:39 UTC
Labels: duplicate
