### ISSUE TITLE
Overhang perimeter not well detected

### ISSUE THREAD

**Issue by ldiegos** [supermerill/SuperSlicer#1562] opened 2021-09-14 06:33 UTC
**Describe the bug**
I have a symmetric design with a section with overhang, but is only detected at one side and in the other side is not detected, so this seems to became an issue when printing because is not properly managed. And seems to squish the layers on that portion.

This is the CAD:
![image](https://user-images.githubusercontent.com/29803600/133206455-dfa88a06-7312-4c2c-b938-a6adbe5c51c3.png)

The section that is correct identified the print is so good, but the section that is not correctly identified is weird:
![image](https://user-images.githubusercontent.com/29803600/133205515-0c745995-1ea3-417b-a5e1-5e3ab6ecc5f8.png)

Despite the position of the model in the bed, the print is always wrong with the squished lines where the overhang starts:
![image](https://user-images.githubusercontent.com/29803600/133206168-bd0b7c29-4b05-4a70-877f-bf21f1d75959.png)

Printed in two different, one with dual z(ender3) the other no. (both are printed without any care, just to show the error, the quality of the overall i know, is bad, stupid fast printed)
![photo_2021-09-14_08-45-22](https://user-images.githubusercontent.com/29803600/133209525-948c11ce-c8d1-4f6e-b55f-de57e555bb1b.jpg)

I design a set of test with different overhangs(with a downgrade version of my CAD program), to see what could be happening, but when i print them, everything is fine, despite one of the overhangs, the one with the angel at 90º, do not show correctly the image.

![image](https://user-images.githubusercontent.com/29803600/133261055-1d43917e-b5ab-43d1-8a15-850ce77d4b67.png)

![image](https://user-images.githubusercontent.com/29803600/133261492-78082df0-c7a2-4dfb-a2d1-4b59edf07542.png)

**To Reproduce**

**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

[TracertAndCompensatorKit-TM45-Zegote.zip](https://github.com/supermerill/SuperSlicer/files/7159332/TracertAndCompensatorKit-TM45-Zegote.zip)

**Expected behavior**
I expect to have the same management of the overhang at both sides. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10Pro
 - Version: 2.3.56.8

**Additional context**

**Comment by gpread** [comment] 2021-09-14 12:21
I have seen the same (or a least very similar) issue but in 2.3.57.0 where overhangs facing the bed which were modelled in the form of a uniform 45 degree chamfer were being inconsistently detected (I didn't print the resulting g-code so can't comment on the resulting squishing aspect).

The chamfer was contiguous on 3 sides of the object but was being detected only in a few of its parts.  I re-sliced with same project file in 2.3.57.9 and it looked fine.

**Comment by ldiegos** [comment] 2021-09-14 12:37
i know what you say @gpread , in my g-code preview one champfer is correctly manange(the front), but both side champfer not.

![image](https://user-images.githubusercontent.com/29803600/133258449-c316948d-fd6d-4e93-9002-7ecf476e1abb.png)

**Comment by gpread** [comment] 2021-09-14 14:03
Well the squishing effects are likely to be somewhat a result of how the printer behaves, start/stop, acceleration/deceleration, retract/unretract are going to increase the likelihood of warping, shrinkage, and under or over extrusion. They may not be at all or only partially due to some error in the slicing.

So I think careful placement of seams when there are overhangs is going to be necessary for high quality prints.

FYI I know that currently (I don't really see it as wrong) Superslicer can/will detect perimeter on first layer as an overhang when XY Compensation of 1st layer is set (to some negative value - to managed so called elephant foot).   So I believe you/we should consider that separately from the inconsistent treatment of uniform overhangs.

Superslicer detects overhangs based on the level of overlap between perimeters, so I can see how other settings and factors can trigger overhang treatment for certain external perimeters, where we might not expect it.

What's not clear (nor I therefore think correct) is why only some part(s) of a perimeter segment should be detected as an overhang.

**Comment by ldiegos** [comment] 2021-09-20 12:38
Hi Supermerill,

Despite the colored overhang that is strange to me... i found my issue with the prints.

Some time ago i was testing and checking the circumference surface and playing with the "filtering/resolution" and i ended up using a 0.009 value to have a nice circular surface without the polygon-ish looking.

But this value, with complex STLs files, make my printers to be overcrowd and do this weir things.

I start from scratch with a ender3 profile were i check that this value was 0.002 and the surface and model are perfect right now, but some of my stl with circular surfaces, have the polygon finish... i will try to increase a little bit more this value to have a balance between finish and structure.

So you can close this "bug" when you want.

Sorry for all the boring stuff.
Luis.

**Comment by supermerill** [comment] 2021-09-27 11:43
@ldiegos using your project file, it's fixed in 2.3.57.0
@gpread for your issue on 2.3.57.0, do you opened/ use an issue where I can reproduce the problem?

**Comment by gpread** [comment] 2021-09-27 11:53
I didn't open an issue on it.  I'll see if I can reproduce again and I'll append to this with details if so

**Comment by gpread** [comment] 2021-09-27 13:59
Susi 2.3.57.0

Windows 20H2 (19042.1165)
CR-10V3 (Modified)
Marlin 2.0.8.2

1.  Load the project file (attached below)
2.  Make sure Print Settings->Perimeters & Shell->Overhangs->Threshold for->Bridge Speed and Fan is set to 55%
3.  Slice the model, then examine the Feature Type view

![image](https://user-images.githubusercontent.com/59426970/134919359-f5415792-2c64-42d0-b25c-3d4d567b75db.png)
4.  Look at the Feature Type view for Overhang Perimeters, on the front of the model running along the x-axis, you can see that the slicer detects only part of the length of a uniform overhang as being one.

![image](https://user-images.githubusercontent.com/59426970/134922568-5e03031c-655e-4cac-a6b6-5138ef2b2fa6.png)
5.  If you  go to Print Settings->Perimeters & Shell->Overhangs->Threshold for->Bridge Speed and Fan adjust from 55% to 56% is will reduce the length it detects as an overhang

![image](https://user-images.githubusercontent.com/59426970/134922928-1f8c9b71-379a-4d49-bae0-a0695a04859d.png)
6. If you  go to Print Settings->Perimeters & Shell->Overhangs->Threshold for->Bridge Speed and Fan adjust from 56% to 57% it will stop detecting that overhang entirely

The same model and 55% setting for overhang threshold for Bridge Speed and Fan does not detect that model feature as an overhang in Susi 2.3.56.9 

So to me, since there is nothing in the model as far as I can tell to make this overhang non-uniform (its clean/no errors and was not constructed with any object/part in that wall at that location), it would seem SuSi 2.3.57.0 is having some strange precision issue triggered by something else about the model.

**Comment by supermerill** [comment] 2021-09-27 14:51
that's due to a over-zealous simplification/precision.
I'll up it a bit.

**Comment by ldiegos** [comment] 2021-09-27 16:48
Thank you so much men!

**Comment by supermerill** [comment] 2021-09-27 18:33
>  jump to the window each time you change a parameter.

?
put 'don't switch' into 'switch to preview when sliced'

**Comment by ldiegos** [comment] 2021-09-27 20:52
> > jump to the window each time you change a parameter.
> 
> ?
> put 'don't switch' into 'switch to preview when sliced'

The problem was detailed over here: https://github.com/supermerill/SuperSlicer/issues/1532 

with version 57.0, if you put "don't switch" the g-code preview" never appear.

**Closed** 2021-10-08 10:30 UTC
Labels: fix is live in the last release
