### ISSUE TITLE
[Feature Request] Port-in of variable width infill as proposed by CNC Kitchen

### ISSUE THREAD

**Issue by fiveangle** [supermerill/SuperSlicer#562] opened 2020-10-12 22:58 UTC
Add variable-width infill as proposed by CNC Kitchen

More information and video: https://www.cnckitchen.com/blog/gradient-infill-for-3d-prints

Initial port was done here: https://github.com/thenickdude/PrusaSlicer/releases/tag/2.2.0-alpha2-variable-width-infill

Which was then submitted as PR to PrusaSlicer branch but is now stale: https://github.com/prusa3d/PrusaSlicer/pull/3517

Originally created against commit: https://github.com/prusa3d/PrusaSlicer/commit/9038dc21e85d1aa956fcb0429659884d028dee66

I attempted to perform a quick FF merge but lots of merge conflicts with changes at the same code locations due to the new variable layer height feature added since then, so manually porting into head would probably be easier.

I've been using the thenickdude build since February whenever I have need for the feature and it has been working quite well, creating robust structural prints.

**Comment by supermerill** [comment] 2020-10-13 12:58
duplicate of #151, please comment on this one.

**Closed by supermerill** 2020-10-13 12:58 UTC
