### ISSUE TITLE
Gap fill causes Gcode output ;WIDTH:-nan(ind) G1 F-nan(ind)

### ISSUE THREAD

**Issue by Thegribbs** [supermerill/SuperSlicer#2102] opened 2021-12-21 22:59 UTC
### What happened?

Enabling gap fill on a specific print causes the Gcode to output a nan at certain sections of code.
I've not had this with other prints, and I'm not sure what settings are causing this on this specific project, or why they've suddenly appeared.
Turning off gap fill fixes the issue.

Here is an example-

`G1 X195.651 Y187.395
G1 X195.254 Y187.243
G1 X194.989 Y187.172
G1 X184.342 Y187.102
G1 Z7.56
G1 E0.5 F4800
;WIDTH:0.359299
G1 F900
;WIDTH:-nan(ind)
G1 F-nan(ind)
G1 X184.189 Y187.158 F10800
;WIDTH:0.221179
G1 F900
G1 X184.342 Y187.102 E0.002
G1 X184.189 Y187.047 E0.002
;WIPE_START
G1 F8640
G1 X184.342 Y187.102 E-0.08608
G1 X184.189 Y187.158 E-0.08608
;WIPE_END`

### Project file & How to reproduce

The issue only appears on certain stl files, such as the one included in the project file attached.

[r2.zip](https://github.com/supermerill/SuperSlicer/files/7758808/r2.zip)

### Version

2.3.57

### Operating system

Windows 10

### Printer model

Ratrig V-Core 3 (klipper)

**Comment by supermerill** [comment] 2021-12-22 10:17
not obvious, but a duplicate of #2099

**Comment by macchinette** [comment] 2021-12-23 12:25
I also wanted to report the problem with a specific project and specific settings.
I confirm that disabling the gap_fill the problem does not arise.
This also happens by keeping the gap_fill active, but by varying the layer height with a value to be found with various tests.
For this project at 0.18 the problem disappears.

Thank you

Windows 10
Version: 2.3.58.0

![image](https://user-images.githubusercontent.com/79080486/147238581-2b847bca-54bd-4968-a9a6-05d6e925b091.png)
[199060.zip](https://github.com/supermerill/SuperSlicer/files/7769277/199060.zip)

**Comment by kesor** [comment] 2021-12-27 17:37
Had the same happen to me today with the latest version

```
;TYPE:Gap fill
;WIDTH:-nan
G1 F1800
G1 X204.359 Y141.738 E-nan
G1 X201.747 Y139.126 E-nan
G1 X201.718 Y139.095 E-nan
G1 E-0.5
G1 Z13.825 F27000
G1 X214.677 Y160.903
G1 Z13.625
G1 E0.5 F1800
```
I uploaded the full sliced gcode file here https://gist.github.com/kesor/6b8c2073778e33055c60c8da14961605

**Comment by supermerill** [comment] 2022-01-04 14:32
@kesor please test with the nightly. Or at least put the project file. The gcode file isn't useful in this case.

**Comment by macchinette** [comment] 2022-01-04 21:57
> @kesor si prega di testare con il serale. O almeno mettere il file di progetto. Il file gcode non è utile in questo caso.

Hi Merill, in my project file with the night version the problem is solved.
Thanks so much

**Closed** 2022-04-01 19:49 UTC
Labels: bug, fix is live in the last release
