### ISSUE TITLE
[Feature Request] adding only one perimeter on BOTTOM surface

### ISSUE THREAD

**Issue by knickohr** [supermerill/SuperSlicer#584] opened 2020-10-19 15:30 UTC
### Version
2.2.54

### Operating system type + version
Win 7 64bit

### 3D printer brand / version + firmware version (if known)
PRUSA Bear (MK2,5s) with SKR Turbo 1.4 and Marlin 2.0.7.x

### Behavior
No problem, only a new feature request :

Adding additional checkbox with "Only one perimeter on BOTTOM surface" in the Print settings, Perimeter & Shell, Quality.

**Comment by supermerill** [comment] 2020-10-19 19:35
duplicate of #289

**Closed by supermerill** 2020-10-19 19:35 UTC
Labels: duplicate
