### ISSUE TITLE
Parallel lines on top of bridge overhang

### ISSUE THREAD

**Issue by JiangMinyang** [supermerill/SuperSlicer#2651] opened 2022-04-06 19:16 UTC
### What happened?

The layer on top of over hang is parallel to over hang lines, not perpendicular. This causes layer adhesion problem with the overhang layer.[](url
<img width="1261" alt="Screen Shot 2022-04-06 at 12 06 54 PM" src="https://user-images.githubusercontent.com/8822658/162050902-0e1fb7cb-c655-49b8-9559-2a9bfe33fae3.png">
<img width="1280" alt="Screen Shot 2022-04-06 at 12 07 03 PM" src="https://user-images.githubusercontent.com/8822658/162050911-34dba69e-5610-400e-b3ea-9536721189e0.png">
)

### Project file & How to reproduce

Turn the model 45 degree (main axis on diagonal of the bed). Slice this stl with support turned on, 0.2 layer height, 0.24 on first layer.  The issue appears on layer 80/81.
[model.zip](https://github.com/supermerill/SuperSlicer/files/8429867/model.zip)

### Version

2.4.58.2

**Comment by neophyl** [comment] 2022-04-07 06:01
You could just set the bridging angle to something else.  Thats what I normally do in these cases.

**Comment by supermerill** [comment] 2022-04-07 09:15
Bridge lines are computed automatically to be on the best orientation.
Infill angle are taken from the setting, and rotated by 90° each layer (+the increment setting).

I don't see how to resolve your problem without rotating the part / changing the settings.

**Comment by supermerill** [comment] 2022-04-07 14:22
> Why + increment?

because it was requested, and there is some uses to it, like cancelling the 90° change at each layer.

> Or just specify repeating pattern of angles like it is done in the simplify3d

duplicate of #2557

**Closed** 2022-04-07 18:11 UTC
Labels: question, working as intended
