### ISSUE TITLE
Spurious M600 on print start with 2.3.56.6b

### ISSUE THREAD

**Issue by greenaar** [supermerill/SuperSlicer#1387] opened 2021-07-03 20:24 UTC
**Describe the bug**

2.3.56.6 adds an M600 after the startup gcode on single color, single filament prints.

**To Reproduce**

Open superslicer 2.3.56.6b
Import a model
Slice
Export the gcode

Look down to the line just above `;LAYER CHANGE` - on 2.3.56.5 that's M107, on 2.3.56.6b it's M600

**>> Project File <<**
[din_clip_double.zip](https://github.com/supermerill/SuperSlicer/files/6758997/din_clip_double.zip)

**Expected behavior**

M600 should not be injected if it has not been explicitly added to the startup gcode, and if the printer is a single nozzle, single extruder using online one color.

**Screenshots**
![image](https://user-images.githubusercontent.com/249029/124366085-e4678680-dc01-11eb-90de-c7b46a5a8eda.png)

**Desktop (please complete the following information):**
Windows
2.3.56.6b

**Additional context**
Not reproduceable on the previous version, but occurs 100% of the time on 2.3.56.6b.

**Comment by supermerill** [comment] 2021-07-03 23:31
duplicate of #1377

**Closed by supermerill** 2021-07-03 23:31 UTC
