### ISSUE TITLE
Acceleration for each move type

### ISSUE THREAD

**Issue by espr14** [supermerill/SuperSlicer#696] opened 2020-11-20 09:02 UTC
### Version
v2.2.54

### Operating system type + version
all

### 3D printer brand / version + firmware version (if known)
all

### Behavior
User can set different speed for different types of movement (external/internal perimeter, infill, support etc.). But it's not just the speed that influences the quality of the print. It's also acceleration and (Marlin) jerk (min. speed, not the physical jerk - mm/s^3). But there's no reason to decrease global acceleration due to external perimeter because it will cause stringing during traveling.

Can you add acceleration and jerk for each type of movement? Since there are acc. and jerk for each axis, there could be just a coefficient (in %) that will decrease both. Would be nice to add junction deviation as well.

I've read this is already available in Cura.

#### Project File (.3MF) where problem occurs

**Comment by supermerill** [comment] 2020-11-21 19:21
* jerk : duplicate of #237
for the acceleration, what is missing from here? 
![image](https://user-images.githubusercontent.com/6536403/99885682-2b86a580-2c37-11eb-87eb-d92798db6f62.png)

**Comment by espr14** [comment] 2020-11-21 20:41
1. Internal vs external perimeter acc.
2. Support acc.
3. Travel acc.
4. Maybe thin extrusion acc.
5. First layer acc.
6. Small perimeter acc.

Would be great to have types in rows and speed/acc./jerk as columns.

**Comment by supermerill** [comment] 2020-11-21 22:08
Adding some new accelerations seems rather easy.

**Comment by espr14** [comment] 2020-11-22 12:01
Printing acceleration defines corner adhesion. But ringing is caused by motors so you want to limit motor acceleration as well.

**Comment by supermerill** [comment] 2020-11-22 12:08
> Printing acceleration
> motor acceleration

what's the difference? there is a gcode for each?

**Comment by espr14** [comment] 2020-11-22 12:47
M201 X1000 Y1000
vs
M204 P800

Motor acceleration is applied to motors directly while printing acceleration is applied to change in direction and speed of printing. Motors with 1000 acc. will achieve 1414 acc. in the diagonal direction.

**Comment by supermerill** [comment] 2020-11-22 13:41
So M204 P800 in the machine limits,
and M201 X1000 Y1000 at each feature change?

and travel acceleration is separate, right?

**Comment by espr14** [comment] 2020-11-22 14:30
All at each feature change. It will create a big matrix and lot of these will be defaults. But you cannot avoid it unless you define tags/modifiers and their hierarchy. E.g.

external_perimeter: acceleration: travel: 3000
external_perimeter: acceleration: printing: 800
external_perimeter: speed: printing: 50

Then you can define sparse matrix more efficiently.

**Comment by x0rtrunks** [comment] 2020-11-27 01:25
M204 would be the preferred way to change acceleration by the user. M201 is the firmware limit.

**Comment by espr14** [comment] 2020-11-27 08:39
Jerk and M201 have impact on ringing in the first place. The other ways are just hotfixes. This is where FW sets limits (Marlin):
```
#define LIMITED_MAX_ACCEL_EDITING     // Limit edit via M201 or LCD to DEFAULT_MAX_ACCELERATION * 2
#if ENABLED(LIMITED_MAX_ACCEL_EDITING)
  #define MAX_ACCEL_EDIT_VALUES       { 6000, 6000, 200, 20000 } // ...or, set your own edit limits
#endif
```

**Comment by astorun** [comment] 2020-12-20 22:56
I would really love to see this feature. Also seperate top solid layer accel/jerk will be awesome!

**Comment by richfelker** [comment] 2021-01-17 21:31
External perimeter acceleration is extremely important and is probably the blocking issue for me switching from Cura to SuperSlicer. Limiting all perimeters to low acceleration makes prints take forever, but high acceleration on external perimeter causes cosmetic and dimensional accuracy problems due to ringing/backlash.

**Comment by richfelker** [comment] 2021-01-17 21:34
Limiting individual motor acceleration should not be done in the gcode emitted by the slicer, or should at least be optional. It's nontrivial how such limits even interact with anything but a straight cartesian printer (e.g. delta, corexy, etc.) and in my experience everyone just treats them as static hard limits for the machine, not as settings to tune dynamically. I wouldn't even be surprised if Marlin has bugs (esp when using JD) with them changing dynamically.

**Comment by VanessaE** [comment] 2021-01-20 08:25
I would like to put my vote in for travel acceleration.

Or if not that, then at the very least, the current behavior should remain, i.e. that no `M204 Txxxx` commands are ever put into the g-code.  At least then the user can still just set it once and then let it be saved in EEPROM.

**Comment by richfelker** [comment] 2021-01-20 17:54
Yes, travel acceleration is important too. I only overlooked it because I use the same (max the machine can reliably handle) acceleration for travel and all parts of print except outer-perimeters, so `default_acceleration` suffices to get the right result for it.

**Comment by richfelker** [comment] 2021-01-20 17:55
For what it's worth, just setting `M204` with `P` and `T` rather than `S` should suffice to get high travel acceleration, but at least Klipper firmware does not honor separate settings here, so having the slicer emit separate `M204 S...` for each change between types of moves is more reliable.

**Comment by zhechenzhu** [comment] 2021-06-10 16:22
+1 for more control over acceleration of different move types. Lower external perimeter acceleration for quality and higher internal for speed.

**Comment by AndrewEllis93** [comment] 2021-10-04 18:52
+1 to this. We are currently working around this with some post-processing scripts and extrusion role change custom gcode, which works but is not ideal.

**Comment by julianschill** [comment] 2021-10-30 17:27
I am currently trying to implement this. This is how it looks like.
![image](https://user-images.githubusercontent.com/13122110/139542772-2e5c876f-38e0-4152-b8b2-8f8f84fbfe3c.png)
My branch can be found here: https://github.com/julianschill/SuperSlicer/tree/julianschill_better_acceleration_control

Is this enough or is there a need to be able to configure accelerations for every type? Is something useful missing? 
 
I am also considering refactoring the whole accelerations code  to a switch/case statement to make it more explicit and better understandable: https://github.com/supermerill/SuperSlicer/blob/403d258c1c5d8cc06a1e608ad7b2c0f661829ef0/src/libslic3r/GCode.cpp#L3867-L3883

Once it's done I could create a pull request, if there is interest.

**Comment by zhechenzhu** [comment] 2021-10-31 03:43
Excellent work. Missing these coming from Cura. Hope to see them merged soon.

**Closed** 2022-04-01 19:49 UTC
Labels: enhancement, fix is live in the last release
