### ISSUE TITLE
Z-Lift modifier doesn't work.

### ISSUE THREAD

**Issue by user32rtu** [supermerill/SuperSlicer#948] opened 2021-02-06 18:48 UTC
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
2.3.55.2
### Operating system type + version
Windows 10 Pro 20H2

### 3D printer brand / version + firmware version (if known)
Sapphire Pro

### Behavior
I am trying to avoid moving the nozzle across the top filled surfaces as the nozzle leaves scars on them.
I am using the height range modifier with a Z-lift override. But no value for Z-lift has any effect.
This only works when Lift Z is set to a non-zero positive value in the filament profile. But in this case Z Lift works on all layers, and I don't need it.

#### Project File (.3MF) where problem occurs
![Screenshot2](https://user-images.githubusercontent.com/48878798/107127036-8047cd00-68c4-11eb-8e44-963d796814da.jpg)
![Screenshot1](https://user-images.githubusercontent.com/48878798/107127037-82aa2700-68c4-11eb-9169-37c67d27557a.jpg)
[Left part.zip](https://github.com/supermerill/SuperSlicer/files/5937429/Left.part.zip)

**Comment by qwewer0** [comment] 2021-02-06 19:33
@user32rtu Make sure that you don't have **Lift Z** set to **0** in **Filament Overrides**.
Don't forget to close the issue if the problem is solved.

**Closed** 2021-02-07 10:09 UTC

**Comment by qwewer0** [comment] 2021-02-07 10:11
@user32rtu Did you find a solution to the problem?

**Comment by Photogad** [comment] 2021-03-13 07:57
Bump
