### ISSUE TITLE
slicer ignores features

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/SuperSlicer#335] opened 2020-07-07 21:12 UTC
### Version
2.2.52
### Operating system type + version
win10
### Behavior
when slicing this the TS100_Top_ file don't get the internal parts with, prusa slicer do with same profile

![image](https://user-images.githubusercontent.com/43273303/86843612-16a1df00-c0a7-11ea-89b4-65935a6298f5.png)
![image](https://user-images.githubusercontent.com/43273303/86843621-1acdfc80-c0a7-11ea-8158-97f917ac406e.png)

#### Project File (.3MF) where problem occurs

[OctoPCB-Alligator-TS100.zip](https://github.com/supermerill/SuperSlicer/files/4887179/OctoPCB-Alligator-TS100.zip)

**Comment by supermerill** [comment] 2020-07-07 22:08
seems like duplicate of duplicate of #334, #327 and #317
fix is in 2.2.52.1

unless it's in 2.2.52.1

**Comment by neophyl** [comment] 2020-07-08 07:26
Just checked the attached 3mf in 2.2.52.1 and the slice looks ok to me.  All the parts are there.

**Closed** 2020-08-24 00:03 UTC
Labels: duplicate, fix is live in the last release
