### ISSUE TITLE
Creating a Bridge Flow calibration with 15% steps and 6 tests causes SuperSlicer to crash

### ISSUE THREAD

**Issue by donicrosby** [supermerill/SuperSlicer#691] opened 2020-11-19 02:15 UTC
### Version
2.2.53

### Operating system type + version
Windows 10 (1904)

### 3D printer brand / version + firmware version (if known)
Prusa MK3S (Firmware 3.9.2)

### Behavior
When you try to create a bridge flow calibration object test for with 15% steps and 6 tests causes SuperSlicer to crash (it can't find the f5.amf bridge flow calibration project)

![image](https://user-images.githubusercontent.com/16298520/99611648-106f2800-29e2-11eb-8b35-07ff6dafd62a.png)
![image](https://user-images.githubusercontent.com/16298520/99611966-a1460380-29e2-11eb-9c9e-52d25b06085a.png)

#### Project File (.3MF) where problem occurs
N/A built in calibration object (see above)

**Comment by supermerill** [comment] 2020-11-19 11:16
thinks for the bug report, I have to add some failsafe.

Testing with 5% flow is a bit extreme.

**Comment by supermerill** [comment] 2020-11-21 20:25
I can't reproduce, can you send me your project file?

**Comment by supermerill** [comment] 2020-11-21 20:30
sorry, that was resolved in the alpha version, but I forgot to push it back on the stable.

**Comment by donicrosby** [comment] 2020-11-24 02:58
Do you want me to close this? Or should I wait until 2.3.x is released to verify before closing?

**Comment by supermerill** [comment] 2020-11-25 12:57
you can verify it works and close it, I'lll close it when doing the next cleaning pass

**Closed** 2021-04-27 19:15 UTC
Labels: bug, fix is live in the last release
