### ISSUE TITLE
Vase Mode Crashes Application

### ISSUE THREAD

**Issue by NortonTech3D** [supermerill/SuperSlicer#3817] opened 2023-04-27 21:39 UTC
### What happened?

When switching to a profile that has vase mode selected or when checking the box to turn on vase mode the application will crash immediately.

### Project file & How to reproduce

[Vase Mode crash.3mf.zip](https://github.com/supermerill/SuperSlicer/files/11348148/Vase.Mode.crash.3mf.zip)

### Version

2.5.59.x

### Operating system

MacOS 12.6.6 (21G633)

### Printer model

Sovol SV01 running Klipper

**Comment by NortonTech-Official** [comment] 2023-04-27 21:40
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SuperSlicer [4399]
Path:                  /Applications/SuperSlicer.app/Contents/MacOS/SuperSlicer
Identifier:            org.SuperSlicer/
Version:               SuperSlicer SuperSlicer_2.5.59.2_2023-04-25 (SuperSlicer_2.5.59.2_2023-04-25)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-27 15:39:48.4341 -0600
OS Version:            macOS 12.6.6 (21G633)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        22B6E5C8-ACA2-189C-A06A-7F1116EDDC6F

Sleep/Wake UUID:       CDB73CF8-9815-45B6-A4E1-DC67BA70F8E8

Time Awake Since Boot: 8100 seconds
Time Since Wake:       6126 seconds

System Integrity Protection: enabled

Crashed Thread:        0  slic3r_main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000000c
Exception Codes:       0x0000000000000001, 0x000000000000000c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4399]

VM Region Info: 0xc is not in any region.  Bytes before following region: 140737486807028
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      VM_ALLOCATE              7fffffe86000-7fffffe87000 [    4K] r-x/r-x SM=ALI  

Thread 0 Crashed:: slic3r_main Dispatch queue: com.apple.main-thread
0   SuperSlicer                   	       0x1056d85f9 Slic3r::DynamicPrintConfig::normalize_fdm() + 1753
1   SuperSlicer                   	       0x105672aca Slic3r::Print::apply(Slic3r::Model const&, Slic3r::DynamicPrintConfig) + 442
2   SuperSlicer                   	       0x105b58303 Slic3r::BackgroundSlicingProcess::apply(Slic3r::Model const&, Slic3r::DynamicPrintConfig const&, Slic3r::DynamicPrintConfig const*) + 163
3   SuperSlicer                   	       0x105da4837 Slic3r::GUI::Plater::priv::update_background_process(bool, bool) + 215
4   SuperSlicer                   	       0x105dd6735 wxEventFunctorFunctor<wxEventTypeTag<wxTimerEvent>, Slic3r::GUI::Plater::priv::priv(Slic3r::GUI::Plater*, Slic3r::GUI::MainFrame*)::$_19>::operator()(wxEvtHandler*, wxEvent&) + 37
5   SuperSlicer                   	       0x107f56fae wxEvtHandler::SearchDynamicEventTable(wxEvent&) + 222
6   SuperSlicer                   	       0x107f56d1b wxEvtHandler::ProcessEventLocally(wxEvent&) + 59
7   SuperSlicer                   	       0x107f56bd9 wxEvtHandler::ProcessEvent(wxEvent&) + 41
8   SuperSlicer                   	       0x107f5714c wxEvtHandler::SafelyProcessEvent(wxEvent&) + 12
9   SuperSlicer                   	       0x107f37b1a wxTimerImpl::SendEvent() + 90
10  CoreFoundation                	    0x7ff809266f49 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
11  CoreFoundation                	    0x7ff809266a38 __CFRunLoopDoTimer + 923
12  CoreFoundation                	    0x7ff8092665a8 __CFRunLoopDoTimers + 307
13  CoreFoundation                	    0x7ff80924ccb6 __CFRunLoopRun + 2010
14  CoreFoundation                	    0x7ff80924be1c CFRunLoopRunSpecific + 562
15  HIToolbox                     	    0x7ff811efb5e6 RunCurrentEventLoopInMode + 292
16  HIToolbox                     	    0x7ff811efb34a ReceiveNextEventCommon + 594
17  HIToolbox                     	    0x7ff811efb0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
18  AppKit                        	    0x7ff80bc85f6d _DPSNextEvent + 927
19  AppKit                        	    0x7ff80bc8462a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
20  AppKit                        	    0x7ff80bc76cd9 -[NSApplication run] + 586
21  SuperSlicer                   	       0x107e7747e wxGUIEventLoop::OSXDoRun() + 174
22  SuperSlicer                   	       0x107f60dfd wxCFEventLoop::DoRun() + 29
23  SuperSlicer                   	       0x107ed65e5 wxEventLoopBase::Run() + 85
24  SuperSlicer                   	       0x107eaee14 wxAppConsoleBase::MainLoop() + 116
25  SuperSlicer                   	       0x107e3c66a wxApp::OnRun() + 26
26  SuperSlicer                   	       0x107f09563 wxEntry(int&, wchar_t**) + 131
27  SuperSlicer                   	       0x105d2d0df Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&) + 239
28  SuperSlicer                   	       0x10515922e Slic3r::CLI::run(int, char**) + 19358
29  SuperSlicer                   	       0x10515d747 main + 375
30  dyld                          	       0x116b8552e start + 462

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff80914a96a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80914acd8 mach_msg + 56
2   CoreFoundation                	    0x7ff80924e34d __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff80924c9d8 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff80924be1c CFRunLoopRunSpecific + 562
5   AppKit                        	    0x7ff80bdf398e _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff8091874e1 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff809182f6b thread_start + 15

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff809182f48 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff809182f48 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff809182f48 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff809182f48 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff809182f48 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000600002a921f0  rcx: 0x0000000000000001  rdx: 0x0000000000000001
  rdi: 0x00000001088a1a30  rsi: 0x00007ff7bada6d38  rbp: 0x00007ff7bada6e30  rsp: 0x00007ff7bada6dd0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000001  r11: 0x00000000000001ff
  r12: 0x7265647572747865  r13: 0x00007ff7bada7df8  r14: 0x00007ff7bada7e18  r15: 0x00007ff7bada7df8
  rip: 0x00000001056d85f9  rfl: 0x0000000000010202  cr2: 0x000000000000000c
  
Logical CPU:     0
Error Code:      0x00000006 (no mapping for user data write)
Trap Number:     14

Thread 0 instruction stream:
  00 00 f6 45 c0 01 74 09-48 8b 7d d0 e8 12 67 96  ...E..t.H.}...g.
  02 c6 45 c0 26 66 0f 10-05 de 33 ff 02 66 0f 11  ..E.&f....3..f..
  45 c1 c7 45 d0 61 74 6f-72 c6 45 d4 00 49 8b 07  E..E.ator.E..I..
  48 8b 40 e8 49 8d 3c 07-49 8b 04 07 48 8d 75 c0  H.@.I.<.I...H.u.
  ba 01 00 00 00 ff 50 20-48 8b 35 10 b3 1a 03 48  ......P H.5....H
  8b 15 81 b3 1a 03 48 89-c7 31 c9 e8 5f 67 96 02  ......H..1.._g..
 [c7]40 0c 00 00 00 00 f6-45 c0 01 74 09 48 8b 7d  .@......E..t.H.}	<==
  d0 e8 ad 66 96 02 c6 45-c0 20 66 0f 10 05 db d8  ...f...E. f.....
  fe 02 66 0f 11 45 c1 c6-45 d1 00 49 8b 07 48 8b  ..f..E..E..I..H.
  40 e8 49 8d 3c 07 49 8b-04 07 48 8d 75 c0 ba 01  @.I.<.I...H.u...
  00 00 00 ff 50 20 48 8b-35 b2 b2 1a 03 48 8b 15  ....P H.5....H..
  13 b3 1a 03 48 89 c7 31-c9 e8 01 67 96 02 c6 40  ....H..1...g...@

Binary Images:
       0x10514c000 -        0x10887bfff org.SuperSlicer/ (SuperSlicer SuperSlicer_2.5.59.2_2023-04-25) <f72dc4c9-9174-32f9-a0d0-33cb730025a1> /Applications/SuperSlicer.app/Contents/MacOS/SuperSlicer
    0x7ff8091ce000 -     0x7ff8096d0fff com.apple.CoreFoundation (6.9) <d39a4db3-a82b-381f-990d-cc6d28628ab3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff811ecd000 -     0x7ff8121c0fff com.apple.HIToolbox (2.1.1) <06fdecd6-9f69-397b-b1e2-a8226c0ba7ed> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff80bc47000 -     0x7ff80cad6fff com.apple.AppKit (6.9) <445ca60e-6d21-3218-8988-f9c99b5a336a> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x116b80000 -        0x116bebfff dyld (*) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld
    0x7ff809149000 -     0x7ff809180fff libsystem_kernel.dylib (*) <066440a4-2cc6-3671-bdb2-610d5e910713> /usr/lib/system/libsystem_kernel.dylib
    0x7ff809181000 -     0x7ff80918cfff libsystem_pthread.dylib (*) <e5d44afd-2577-3cee-8711-9d8d426229e0> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=849.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=849.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG backing stores                 2160K        4 
CG image                          4300K      111 
CG raster data                    1476K       78 
ColorSync                          232K       28 
CoreAnimation                    198.3M      171 
CoreGraphics                        12K        2 
CoreImage                           32K        7 
CoreUI image data                 5004K       41 
Foundation                          36K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           246.8M       68 
MALLOC guard page                   32K        8 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
ObjC additional data                15K        1 
OpenGL GLSL                        256K        3 
STACK GUARD                       56.0M        7 
Stack                             11.1M        8 
VM_ALLOCATE                       2128K      127 
__CTF                               756        1 
__DATA                            25.6M      398 
__DATA_CONST                      24.6M      246 
__DATA_DIRTY                      1014K      144 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       669.3M       10 
__TEXT                           487.6M      418 
__UNICODE                          592K        1 
dyld private memory               1536K        3 
mapped file                      172.2M       33 
shared memory                      780K       18 
===========                     =======  ======= 
TOTAL                              2.2G     1948 
TOTAL, minus reserved VM space     1.9G     1948 



-----------
Full Report
-----------

{"app_name":"SuperSlicer","timestamp":"2023-04-27 15:39:49.00 -0600","app_version":"SuperSlicer SuperSlicer_2.5.59.2_2023-04-25","slice_uuid":"f72dc4c9-9174-32f9-a0d0-33cb730025a1","build_version":"SuperSlicer_2.5.59.2_2023-04-25","platform":1,"bundleID":"org.SuperSlicer\/","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.6 (21G633)","incident_id":"7C9E9465-3EB8-4D09-A6A6-78614E9165B1","name":"SuperSlicer"}
{
  "uptime" : 8100,
  "procLaunch" : "2023-04-27 15:36:06.3933 -0600",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro13,2",
  "procStartAbsTime" : 7964797998619,
  "coalitionID" : 2207,
  "osVersion" : {
    "train" : "macOS 12.6.6",
    "build" : "21G633",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-27 15:39:48.4341 -0600",
  "incident" : "7C9E9465-3EB8-4D09-A6A6-78614E9165B1",
  "bug_type" : "309",
  "pid" : 4399,
  "procExitAbsTime" : 8186824871418,
  "cpuType" : "X86-64",
  "procName" : "SuperSlicer",
  "procPath" : "\/Applications\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer",
  "bundleInfo" : {"CFBundleShortVersionString":"SuperSlicer SuperSlicer_2.5.59.2_2023-04-25","CFBundleVersion":"SuperSlicer_2.5.59.2_2023-04-25","CFBundleIdentifier":"org.SuperSlicer\/"},
  "storeInfo" : {"deviceIdentifierForVendor":"CB353065-48CE-5309-A46B-648DCAA98929","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.SuperSlicer\/",
  "crashReporterKey" : "22B6E5C8-ACA2-189C-A06A-7F1116EDDC6F",
  "wakeTime" : 6126,
  "bridgeVersion" : {"build":"14Y910","train":"3.0"},
  "sleepWakeUUID" : "CDB73CF8-9815-45B6-A4E1-DC67BA70F8E8",
  "sip" : "enabled",
  "vmRegionInfo" : "0xc is not in any region.  Bytes before following region: 140737486807028\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      VM_ALLOCATE              7fffffe86000-7fffffe87000 [    4K] r-x\/r-x SM=ALI  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x000000000000000c","rawCodes":[1,12],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x000000000000000c"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":4399},
  "vmregioninfo" : "0xc is not in any region.  Bytes before following region: 140737486807028\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      VM_ALLOCATE              7fffffe86000-7fffffe87000 [    4K] r-x\/r-x SM=ALI  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"queue":"com.apple.main-thread","instructionState":{"instructionStream":{"bytes":[0,0,246,69,192,1,116,9,72,139,125,208,232,18,103,150,2,198,69,192,38,102,15,16,5,222,51,255,2,102,15,17,69,193,199,69,208,97,116,111,114,198,69,212,0,73,139,7,72,139,64,232,73,141,60,7,73,139,4,7,72,141,117,192,186,1,0,0,0,255,80,32,72,139,53,16,179,26,3,72,139,21,129,179,26,3,72,137,199,49,201,232,95,103,150,2,199,64,12,0,0,0,0,246,69,192,1,116,9,72,139,125,208,232,173,102,150,2,198,69,192,32,102,15,16,5,219,216,254,2,102,15,17,69,193,198,69,209,0,73,139,7,72,139,64,232,73,141,60,7,73,139,4,7,72,141,117,192,186,1,0,0,0,255,80,32,72,139,53,178,178,26,3,72,139,21,19,179,26,3,72,137,199,49,201,232,1,103,150,2,198,64],"offset":96}},"frames":[{"imageOffset":5817849,"symbol":"Slic3r::DynamicPrintConfig::normalize_fdm()","symbolLocation":1753,"imageIndex":0},{"imageOffset":5401290,"symbol":"Slic3r::Print::apply(Slic3r::Model const&, Slic3r::DynamicPrintConfig)","symbolLocation":442,"imageIndex":0},{"imageOffset":10535683,"symbol":"Slic3r::BackgroundSlicingProcess::apply(Slic3r::Model const&, Slic3r::DynamicPrintConfig const&, Slic3r::DynamicPrintConfig const*)","symbolLocation":163,"imageIndex":0},{"imageOffset":12945463,"symbol":"Slic3r::GUI::Plater::priv::update_background_process(bool, bool)","symbolLocation":215,"imageIndex":0},{"imageOffset":13150005,"symbol":"wxEventFunctorFunctor<wxEventTypeTag<wxTimerEvent>, Slic3r::GUI::Plater::priv::priv(Slic3r::GUI::Plater*, Slic3r::GUI::MainFrame*)::$_19>::operator()(wxEvtHandler*, wxEvent&)","symbolLocation":37,"imageIndex":0},{"imageOffset":48279470,"symbol":"wxEvtHandler::SearchDynamicEventTable(wxEvent&)","symbolLocation":222,"imageIndex":0},{"imageOffset":48278811,"symbol":"wxEvtHandler::ProcessEventLocally(wxEvent&)","symbolLocation":59,"imageIndex":0},{"imageOffset":48278489,"symbol":"wxEvtHandler::ProcessEvent(wxEvent&)","symbolLocation":41,"imageIndex":0},{"imageOffset":48279884,"symbol":"wxEvtHandler::SafelyProcessEvent(wxEvent&)","symbolLocation":12,"imageIndex":0},{"imageOffset":48151322,"symbol":"wxTimerImpl::SendEvent()","symbolLocation":90,"imageIndex":0},{"imageOffset":626505,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__","symbolLocation":20,"imageIndex":1},{"imageOffset":625208,"symbol":"__CFRunLoopDoTimer","symbolLocation":923,"imageIndex":1},{"imageOffset":624040,"symbol":"__CFRunLoopDoTimers","symbolLocation":307,"imageIndex":1},{"imageOffset":519350,"symbol":"__CFRunLoopRun","symbolLocation":2010,"imageIndex":1},{"imageOffset":515612,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":2},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":2},{"imageOffset":188645,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":2},{"imageOffset":257901,"symbol":"_DPSNextEvent","symbolLocation":927,"imageIndex":3},{"imageOffset":251434,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1394,"imageIndex":3},{"imageOffset":195801,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":3},{"imageOffset":47363198,"symbol":"wxGUIEventLoop::OSXDoRun()","symbolLocation":174,"imageIndex":0},{"imageOffset":48319997,"symbol":"wxCFEventLoop::DoRun()","symbolLocation":29,"imageIndex":0},{"imageOffset":47752677,"symbol":"wxEventLoopBase::Run()","symbolLocation":85,"imageIndex":0},{"imageOffset":47590932,"symbol":"wxAppConsoleBase::MainLoop()","symbolLocation":116,"imageIndex":0},{"imageOffset":47122026,"symbol":"wxApp::OnRun()","symbolLocation":26,"imageIndex":0},{"imageOffset":47961443,"symbol":"wxEntry(int&, wchar_t**)","symbolLocation":131,"imageIndex":0},{"imageOffset":12456159,"symbol":"Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&)","symbolLocation":239,"imageIndex":0},{"imageOffset":53806,"symbol":"Slic3r::CLI::run(int, char**)","symbolLocation":19358,"imageIndex":0},{"imageOffset":71495,"symbol":"main","symbolLocation":375,"imageIndex":0},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":4}],"id":111258,"triggered":true,"threadState":{"r13":{"value":140701968530936},"rax":{"value":0},"rflags":{"value":66050},"cpu":{"value":0},"r14":{"value":140701968530968},"rsi":{"value":140701968526648},"r8":{"value":0},"cr2":{"value":12},"rdx":{"value":1},"r10":{"value":1},"r9":{"value":0},"r15":{"value":140701968530936},"rbx":{"value":105553160905200},"trap":{"value":14,"description":"(no mapping for user data write)"},"err":{"value":6},"r11":{"value":511},"rip":{"value":4386031097,"matchesCrashFrame":1},"rbp":{"value":140701968526896},"rsp":{"value":140701968526800},"r12":{"value":8243105148565747813},"rcx":{"value":1},"flavor":"x86_THREAD_STATE","rdi":{"value":4438235696,"symbolLocation":0,"symbol":"typeinfo for Slic3r::ConfigOption"}},"name":"slic3r_main"},{"id":111309,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":5},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":5},{"imageOffset":525133,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":518616,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":515612,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":1755534,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":3},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":6},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":112574,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":112692,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":112936,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":113998,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":114004,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4380213248,
    "CFBundleShortVersionString" : "SuperSlicer SuperSlicer_2.5.59.2_2023-04-25",
    "CFBundleIdentifier" : "org.SuperSlicer\/",
    "size" : 57868288,
    "uuid" : "f72dc4c9-9174-32f9-a0d0-33cb730025a1",
    "path" : "\/Applications\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer",
    "name" : "SuperSlicer",
    "CFBundleVersion" : "SuperSlicer_2.5.59.2_2023-04-25"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703281504256,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "d39a4db3-a82b-381f-990d-cc6d28628ab3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703429349376,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "06fdecd6-9f69-397b-b1e2-a8226c0ba7ed",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703326040064,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15269888,
    "uuid" : "445ca60e-6d21-3218-8988-f9c99b5a336a",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4676124672,
    "size" : 442368,
    "uuid" : "2517e9fe-884a-3855-8532-92bffba3f81c",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703280959488,
    "size" : 229376,
    "uuid" : "066440a4-2cc6-3671-bdb2-610d5e910713",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703281188864,
    "size" : 49152,
    "uuid" : "e5d44afd-2577-3cee-8711-9d8d426229e0",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703277932544,
  "size" : 19331678208,
  "uuid" : "f867de15-df38-3cbd-af3b-0a0a3f85319e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=849.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=849.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               640K        5 \nActivity Tracing                   256K        1 \nCG backing stores                 2160K        4 \nCG image                          4300K      111 \nCG raster data                    1476K       78 \nColorSync                          232K       28 \nCoreAnimation                    198.3M      171 \nCoreGraphics                        12K        2 \nCoreImage                           32K        7 \nCoreUI image data                 5004K       41 \nFoundation                          36K        2 \nKernel Alloc Once                    8K        1 \nMALLOC                           246.8M       68 \nMALLOC guard page                   32K        8 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nObjC additional data                15K        1 \nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.0M        7 \nStack                             11.1M        8 \nVM_ALLOCATE                       2128K      127 \n__CTF                               756        1 \n__DATA                            25.6M      398 \n__DATA_CONST                      24.6M      246 \n__DATA_DIRTY                      1014K      144 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       669.3M       10 \n__TEXT                           487.6M      418 \n__UNICODE                          592K        1 \ndyld private memory               1536K        3 \nmapped file                      172.2M       33 \nshared memory                      780K       18 \n===========                     =======  ======= \nTOTAL                              2.2G     1948 \nTOTAL, minus reserved VM space     1.9G     1948 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "slic3r_main",
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 250000011
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 250000230
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro13,2, BootROM 509.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.9 GHz, 8 GB, SMC 2.37f25
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: Tailscale Tunnel, VPN (io.tailscale.ipn.macos), utun3
USB Device: USB30Bus
USB Device: SteelSeries Aerox 3 Wireless
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.5

**Comment by DarKingF0x** [comment] 2023-04-29 06:13
I'm also having this problem. I thought it was my pc at first so I uninstalled and reinstalled the same version and vase mode continuously crashes the app.

**Comment by timschneider** [comment] 2023-05-02 10:36
duplicate of #3749 #3731 #3722 #3715 fixed with #3736

**Closed** 2023-11-22 16:38 UTC
