### ISSUE TITLE
Changing the custom code on layer bar doesn't flag a change in a project

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4261] opened 2024-05-15 18:50 UTC
If I change something in custom code I have to save as instead of just save.

**Comment by TheSlashEffect** [comment] 2024-06-27 21:39
None of the choices per layer (editing/adding custom gcode, pause, or colour change) flag a change in the project. I have fixed this and will create a PR soon.

**Comment by TheSlashEffect** [comment] 2024-06-28 12:24
Duplicate of #2645

**Closed** 2024-07-01 17:07 UTC
Labels: bug, fixed for the next version
