### ISSUE TITLE
Bug?: "solid Infill" Allways on with 2 Perimeters

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#605] opened 2020-10-26 11:05 UTC
### Version
2.2.54

### Behavior
Even disabling all options for solid fill, always appearing.
![image](https://user-images.githubusercontent.com/38788588/97163314-60a6f180-1778-11eb-8134-8be522715e53.png)
[3DBenchy.zip.amf.zip](https://github.com/supermerill/SuperSlicer/files/5438385/3DBenchy.zip.amf.zip)

**Comment by neophyl** [comment] 2020-10-26 11:20
That's because its not normal solid infill.  Its a known issue in Prusa Slicer and is related to vertical shell thickness on sloping walls but it happens regardless of if that option is checked or not too.  So yes technically a bug but exists in Prusa Slicer currently and historically.

**Comment by supermerill** [comment] 2020-10-26 14:10
duplicate of https://github.com/supermerill/SuperSlicer/issues/253

**Closed** 2020-10-27 00:35 UTC
Labels: duplicate
