### ISSUE TITLE
Relative Extrusion GCODE

### ISSUE THREAD

**Issue by nicedevil007** [supermerill/SuperSlicer#2518] opened 2022-03-12 08:34 UTC
**Bug description**
I get gaps on the outer walls as I turn on Relative Extrusions.

**Expected behavior**
No Gaps on the outer walls.

!!>> Project File <<!!
I can't share the stl/project as wanted because it is a non free STL.
What I can share is my config itself.
[SuperSlicer_config_bundle.zip](https://github.com/supermerill/SuperSlicer/files/8237292/SuperSlicer_config_bundle.zip)

**To Reproduce**

1. Enable Relative Extrusions

**Screenshots**
Without the checkmark of relative Extrusions:
![image](https://user-images.githubusercontent.com/17103076/158010453-f18b5ecf-98a1-456f-beaa-a0578e8b67cf.png)

With checkmark of relative Extrusions:
![image](https://user-images.githubusercontent.com/17103076/158010535-f89354db-670e-42b7-a48f-6227a6b0eeae.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.4.58.1 (latest nightly per now)
 - Printer model: RR VCore3

**Comment by supermerill** [comment] 2022-03-12 13:07
duplicate of #2484

**Closed** 2022-03-13 12:12 UTC
Labels: duplicate
