### ISSUE TITLE
When you save the r code, the name in Russian turns into gibberish, can you fix it? 

### ISSUE THREAD

**Issue by AKlionRU** [supermerill/SuperSlicer#964] opened 2021-02-19 13:38 UTC
### Version
2.3.55

### Operating system type + version
macOS Big Sur

When you save the r code, the name in Russian turns into gibberish, can you fix it? 
![Снимок экрана 2021-02-19 в 17 34 00](https://user-images.githubusercontent.com/76438933/108511290-26d69980-72d9-11eb-9ce9-4d622683c555.png)

**Comment by supermerill** [comment] 2021-02-22 17:11
can't reproduce, i need your project file.

**Comment by AKlionRU** [comment] 2021-02-22 17:35
Here is a file with a Russian name 
[Коробка Natase.STL.zip] (https://github.com/supermerill/SuperSlicer/files/6023921/STL.zip)

**Comment by supermerill** [comment] 2021-02-24 19:19
can't reproduce on my windows
![image](https://user-images.githubusercontent.com/6536403/109052730-3b050700-76dc-11eb-961d-907a819c1df2.png)

that may come from the "fold to acsii" function the file name passed by.
basically, it changes unicode character to ascii one to be sure the os can handle it as filename.

I don't know how to resolve it without creating more bugs.

**Comment by AKlionRU** [comment] 2021-02-24 20:48
The latest version of PrusaSlicer does not have this bug. there very simply solved this problem

**Comment by supermerill** [comment] 2021-06-26 01:06
fixed now. But the russian transaltion needs a native speaker to help me with translation.

**Closed by supermerill** 2021-06-26 01:06 UTC
Labels: could not reproduce
