### ISSUE TITLE
generated 2.4.58 presets not backward compatible : "Invalid value provided for parameter thin_perimeters: 100%"

### ISSUE THREAD

**Issue by netweaver1970** [supermerill/SuperSlicer#2526] opened 2022-03-13 12:44 UTC
### What happened?

All newly created (or modified and saved) presets in the new (beta) Master version are not compatible with the Stable version, making it very impractical to switch between Stable and Master (or nightly).
When opening the Stable release, one gets a pop-up with -for each 'invalid' preset- the below text in the message box. And SS closes. The only thing you can do is manually edit the preset text file, remove the offending line in all presets 'touched' by the Master release. This setting is the only one giving issues, so maybe Master can be adjusted to create backwards compatible preset files.

```
Failed loading the preset file: C:\Users\xxxx\AppData\Roaming\SuperSlicer\print\GS_0.2mm 0.4nozzle_TPU.ini
Reason: Failed loading configuration file "C:\Users\xxxx\AppData\Roaming\SuperSlicer\print\GS_0.2mm 0.4nozzle_TPU.ini": Invalid value provided for parameter thin_perimeters: 100%
```

### Project file & How to reproduce

Just open up a preset in Master, change something, save it.
Then try to open Stable, and it will give the error and close down.

### Version

2.4.58.1

### Operating system

WIndows 10

### Printer model

Voron 2.4 with Mantis

**Comment by supermerill** [comment] 2022-03-13 14:25
duplicate of #2510

**Closed** 2022-03-13 14:52 UTC
Labels: duplicate
