### ISSUE TITLE
Gap fill causing excessive travel moves

### ISSUE THREAD

**Issue by WarriorMe** [supermerill/SuperSlicer#728] opened 2020-11-28 00:36 UTC
### Version
2.2.53

### Operating system type + version
Windows 10 64bit

### 3D printer brand / version + firmware version (if known)
RepRap Firmware 2.04

### Behavior
Shallow angle between solid infill and perimeter generates gap fill

The gap fill is printed last on each layer instead of together with the infill, significantly increasing print time and unneccesarily dragging the nozzle over the part if there is no Z-Hop

![Gap FIll](https://user-images.githubusercontent.com/75147743/100490135-51b9b300-3119-11eb-8bad-7981574eaba7.PNG)

![Gap FIll 2](https://user-images.githubusercontent.com/75147743/100490145-6c8c2780-3119-11eb-974b-85e936ec7ae8.PNG)

#### Project File (.3MF) where problem occurs
[Frame.zip](https://github.com/supermerill/SuperSlicer/files/5609873/Frame.zip)

**Comment by supermerill** [comment] 2020-11-28 18:03
duplicate of #585

**Closed** 2020-11-28 18:04 UTC
Labels: duplicate
