### ISSUE TITLE
Option to force alternating perimeter printing direction every other layer

### ISSUE THREAD

**Issue by timnk** [supermerill/SuperSlicer#4159] opened 2024-02-27 16:25 UTC
**Is your feature request related to a problem? Please describe.**
When printing and sintering metal or ceramic filled filaments, the inner tensions in the part introduced by printing every perimeter in the same direction results in a twisted geometry after sintering.

**Describe the solution you'd like**
This problem can be resolved by reversing the printing direction ov the perimeters every other layer. I would like to have an experimental option that would do this in SuperSlicer. A simple checkbox in the GUI would be perfect. It could be located either unter Print Settings -> Periemters & Shells or somewhere under Filament Settings, since it is really only needed for specific filaments.

**Describe how it would work**
It seems like SuperSlicer is already capible of reversing the printing direction, because the parameter "overhangs_reverse" exists. Maybe this coud be built upon?

**Describe alternatives you've considered**
so far I have unsucessfully tried to get Cura and IdeaMaker working, since they have this feature implemented as far as i know. However I find the Interfaces unnessesary complicated and I am a lot more familiar with SuperSlicer.

I hope i could describe my suggestion sufficently and see it implemented in the future

In any case,
Thank you for developing this awesome software!

**Comment by supermerill** [comment] 2024-02-29 12:38
it will be in next 2.5 nightly.
But it won't be merged into the next 2.5 release, as it's not a bugfix (will be in 2.7).

**Closed** 2024-05-21 12:15 UTC
Labels: new Feature, fix is live in the last release
