### ISSUE TITLE
My if/else filament logic is no longer working in 2.2.54

### ISSUE THREAD

**Issue by AndrewEllis93** [supermerill/SuperSlicer#544] opened 2020-10-08 05:11 UTC
### Version
2.2.54

### Operating system type + version
Win 10 Pro latest

### 3D printer brand / version + firmware version (if known)
Voron 2

### Behavior
I use if/else logic in my filaments' custom gcode to set pressure advance per printer profile. For example:

{if printer_settings_id == "Voron-HF 0.4"} SET_PRESSURE_ADVANCE ADVANCE=0.051
{endif}

In 2.2.53, this would succesfully add the appropriate pressure advance line into the gcode.
In 2.2.54 with the exact same config, it no longer works. 
I tested back to back in each version using the same 3mf file (attached).

#### Project File (.3MF) where problem occurs
[Example.zip](https://github.com/supermerill/SuperSlicer/files/5345417/Example.zip)

**Comment by supermerill** [comment] 2020-10-08 08:25
Duplicate of #533 #534 #542

**Closed** 2020-10-28 21:14 UTC
Labels: duplicate, fix is live in the last release
