### ISSUE TITLE
can't export Configuration

### ISSUE THREAD

**Issue by SidewalkPsycho** [supermerill/SuperSlicer#613] opened 2020-10-29 15:08 UTC
### Version
V2.2.53

### Operating system type + version
Win 10 64 bit

### Behavior
Hi there, i can't export my configuration. I get the error message : value out of range: filament_shrink.
but it's at 100% as you can see in the attached screenshot.
https://prnt.sc/v9h57m

**Comment by supermerill** [comment] 2020-10-29 15:34
seems like a duplicate of #528

Did it also happens with the 2.2.53.3 ?

**Comment by timoleary** [comment] 2020-10-30 00:58
> seems like a duplicate of #528
> 
> Did it also happens with the 2.2.53.3 ?

Can confirm the problem exists with SuperSlicer_2.2.53.3_win64_20201005

**Comment by StefanoPerinetti** [comment] 2020-10-30 09:37
Yes I can confirm that the problem exist also in latest Mac Version SuperSlicer_2.2.53.3_macos_20201005.dmg

**Comment by StefanoPerinetti** [comment] 2020-10-30 09:41
<img width="1073" alt="Schermata 2020-10-30 alle 10 38 09" src="https://user-images.githubusercontent.com/68896926/97689599-1d13f680-1a9c-11eb-907d-e553f26e44a6.png">

<img width="999" alt="Schermata 2020-10-30 alle 10 38 23" src="https://user-images.githubusercontent.com/68896926/97689564-0c638080-1a9c-11eb-9288-56c8dcad7b91.png">

<img width="981" alt="Schermata 2020-10-30 alle 10 40 25" src="https://user-images.githubusercontent.com/68896926/97689751-58162a00-1a9c-11eb-96d5-55efc1ebcd76.png">

**Comment by StefanoPerinetti** [comment] 2020-10-30 09:43
I download the precompiled file from github releases but I don't know if it contain the latest version
<img width="244" alt="Schermata 2020-10-30 alle 10 43 50" src="https://user-images.githubusercontent.com/68896926/97690101-ce1a9100-1a9c-11eb-9eae-ceaf96545ad7.png">

**Comment by supermerill** [comment] 2020-11-02 23:01
ok, it was fixed the day after the 2.2.53.3 release... time for a 2.2.53.4

**Comment by StefanoPerinetti** [comment] 2020-11-03 08:06
Ok thank you!

**Closed** 2020-11-25 12:57 UTC
Labels: bug, fix is live in the last release
