### ISSUE TITLE
Italian translation Bsod 

### ISSUE THREAD

**Issue by MicheleC11** [supermerill/SuperSlicer#1004] opened 2021-03-12 14:16 UTC
### Version
2.3.55.5 Italian

### Operating system type + version
MacOS 10.15.7

### 3D printer brand + version
_Artillery genius_

### Behavior
* _SuperSlicer crashes when I access: filament settings -> cooling_
* _I expect you to fix the problem and let me access the settings_

**Comment by supermerill** [comment] 2021-03-13 17:02
There's a problem in the italian translation.

**Comment by supermerill** [comment] 2021-03-13 17:05
duplicate of #1003

**Comment by boromyr** [comment] 2021-04-30 19:41
[Problem solved](https://github.com/supermerill/SuperSlicer/issues/1128)

**Closed** 2021-06-04 16:47 UTC
Labels: bug, duplicate, fix is live in the last release
