### ISSUE TITLE
wxWidgets error during 2.3.56.0 startup (WIN64)

### ISSUE THREAD

**Issue by kintarojs** [supermerill/SuperSlicer#1183] opened 2021-05-25 18:17 UTC
wxWidgets throw an alert during the application startup on 2.3.56.0 win64 version.
No custom, appears when I run the exe just after the unzip & after each change in right menu.

![image](https://user-images.githubusercontent.com/16974550/119547978-07e31a00-bd96-11eb-8373-23711f6ee2a5.png)
![image](https://user-images.githubusercontent.com/16974550/119548075-20533480-bd96-11eb-92af-7c4dc379a007.png)

OS: win10 20H2

**Comment by supermerill** [comment] 2021-05-25 18:25
duplicate of #1166

**Closed by supermerill** 2021-05-25 18:25 UTC
