### ISSUE TITLE
Extrusion width became greyed out

### ISSUE THREAD

**Issue by erictioh** [supermerill/SuperSlicer#2233] opened 2022-01-16 11:55 UTC
### What happened?

I don't know what have i done and this just became greyed out, and i'm sure it wasn't like this before.

When i switch back to any of those system default template, it will allow for edit again.

Wish to know what is the logic behind to for these 2 to be greyed out if this is not bug.

### Project file & How to reproduce

Not sure.

### Version

2.3.57.9

### Operating system

Windows 11

### Printer model

Creality CR10 modded

![image](https://user-images.githubusercontent.com/44055730/149658903-d7b5bc8f-9b36-412f-b031-c07a7fcc07bd.png)

**Comment by supermerill** [comment] 2022-01-17 00:17
duplicate of #2137

**Closed** 2022-01-17 00:17 UTC
Labels: duplicate
