### ISSUE TITLE
Over extrusion in gap fill

### ISSUE THREAD

**Issue by pbutler** [supermerill/SuperSlicer#519] opened 2020-10-01 19:03 UTC
### Version
2.2.53
### Operating system type + version
OSX 10.15.4

### 3D printer brand / version + firmware version (if known)
Custom DBot style running Duet RepRapFirmware 3.1

### Behavior

When Gap fill is enabled, it seems to over-extrude causing edges with a lot of artifacts.  This is extremely noticeable on small parts.    Turning off gap fill fixes this but there is of course gaps. This doesn't seem to happen with similar settings on PrusaSlicer with gap fill enabled.  It seems to be an artifact of the variable width extrusion of the gap fill in super slicer.

_Is this a new feature request?_ No

#### Project File (.3MF) where problem occurs
[gear.stl.zip](https://github.com/supermerill/SuperSlicer/files/5314235/gear.stl.zip).

**Comment by supermerill** [comment] 2020-10-01 19:16
duplicate of #512

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate
