### ISSUE TITLE
Worse Surface Quality than Before (2.3.55.3 and above)

### ISSUE THREAD

**Issue by derizk-cpu** [supermerill/SuperSlicer#961] opened 2021-02-16 13:44 UTC
### Version
2.3.55.3 - 2.3.55.4

### Operating system type + version
Windows 10 

### 3D printer brand / version + firmware version (if known)
Prusa Mini (latest firmware)

### Behavior
* Finish quality of the walls is inconsistent, which results in worse quality in the actual print.

(I've been able to deduce that it's the result of changes from Dec 8, 2020. I believe it may result from dropping the minimum resolution, however changing the resolution in the slicer has no effect on the issue. Nothing in-slicer changed anything.)

* Create a cylinder in the slicer and look at the resulting g-code preview from an upward angle.
* Expected uniform-looking layers with only slight marks at the seam.
* Actually see non-circular extrusions which make the surface rough.

![2 3 55 4](https://user-images.githubusercontent.com/55260190/108070762-e2c26b00-7032-11eb-89cc-9610785e7fdf.JPG)
2.3.55.4 Close-up with 0.08mm layers and random seam placement

![2 3 55 2](https://user-images.githubusercontent.com/55260190/108070836-f8d02b80-7032-11eb-9746-065f73a33ba4.JPG)
2.3.55.2 (stable version) Same settings

#### Project File (.3MF) where problem occurs
Applies to all models (create shape)

**Comment by CCS86** [comment] 2021-02-23 22:37
Check out this setting. I was playing around and found that zeroing it out reproduced your issue:

![image](https://user-images.githubusercontent.com/12439543/108917462-619c4280-75f5-11eb-848c-9c5dc04dc99e.png)

![image](https://user-images.githubusercontent.com/12439543/108917472-6660f680-75f5-11eb-87c4-42dc2e7807c3.png)

**Comment by CCS86** [comment] 2021-02-24 02:54
Playing around, values like 0.00005 worked just a touch better in trouble spots.

**Comment by robthide37** [comment] 2021-02-27 00:20
dos th nwst build fix this ? it is noted but does not say

**Comment by derizk-cpu** [comment] 2021-02-27 03:24
@robthide37 No, it's still an issue for me.

**Comment by CCS86** [comment] 2021-02-27 03:58
> @robthide37 No, it's still an issue for me.

Did you read my posts?

**Comment by derizk-cpu** [comment] 2021-02-27 04:13
@CCS86 I did. It's better, but it doesn't look the same as your result. I'm using the latest 2.3.55.5 version.

![Weird](https://user-images.githubusercontent.com/55260190/109375097-02099580-7888-11eb-80d0-27ae96169813.JPG)
Resolution Set to 0, Rounding Precision at 0.00001, and Slice Gap Closing Radius at 0.049.
Prusa Mini 0.10mm Detail preset with seam position set to random.

**Comment by CCS86** [comment] 2021-02-27 16:13
You should still upload the project file. No one can recreate all your settings without it.

**Comment by derizk-cpu** [comment] 2021-02-28 01:40
@CCS86 

[Resolution Weirdness.zip](https://github.com/supermerill/SuperSlicer/files/6056122/Resolution.Weirdness.zip)

Open with the latest release and compare it with the last one.

**Comment by CCS86** [comment] 2021-03-01 19:20
It appears that having a randomized seam placement is causing this. Switch to aligned and it goes away. 

This makes sense, since the segment layout is relative to the seam, and if your seam is truly random, your segment start/ends will be random and cause this.

**Comment by derizk-cpu** [comment] 2021-03-01 23:12
> 
> 
> It appears that having a randomized seam placement is causing this. Switch to aligned and it goes away.
> 
> This makes sense, since the segment layout is relative to the seam, and if your seam is truly random, your segment start/ends will be random and cause this.

That _IS_ true, but what if I want to use random seam placement? In older versions the preview looked just like the aligned preview with the seam in random places (see first comparison). A circular path should make the same line regardless of where it starts and ends the seam. Furthermore, on more complex geometry, aligned seam position won't always have the seam in a vertical line, so you'll end up with similar artifacts to random.

Both PrusaSlicer and Cura handle random seams correctly.

**Comment by CCS86** [comment] 2021-03-02 01:10
I'm with you. I think handling segment alignment independently of seam placement would be best.

Just trying to add some context to help @supermerill

**Comment by CCS86** [comment] 2021-03-10 21:11
I found a situation where even with an aligned seam and tightened rounding precision, the surface is inconsistant:

![image](https://user-images.githubusercontent.com/12439543/110697985-aeb21400-81b2-11eb-884c-e5d93cb616cf.png)


[Tap Align - M10.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6118875/Tap.Align.-.M10.3mf.txt)

**Comment by Photogad** [comment] 2021-03-13 07:55
Bump

**Comment by robthide37** [comment] 2021-03-13 15:22
try turning off reverse on odd ?

**Comment by CCS86** [comment] 2021-03-15 15:21
> try turning off reverse on odd ?


That's off for me.

**Comment by robthide37** [comment] 2021-03-16 01:10
oh

**Comment by supermerill** [comment] 2021-03-18 13:17
It's a very concerning problem. I tried to increase the precision, and it seems that it has the opposite result.

**Comment by derizk-cpu** [comment] 2021-03-29 12:23
@supermerill Unfortunately, putting 0 into "Resolution" and "Min segment length" doesn't really fix the issue. Even with the same settings, the older versions generate perimeters differently. The current versions don't align the perimeters correctly.

**Comment by supermerill** [comment] 2021-04-24 00:37
I think i found the bug
![image](https://user-images.githubusercontent.com/6536403/115941517-f7ddcf00-a4a5-11eb-93a9-ca85bbdf15e0.png)
fix will come shortly

**Comment by derizk-cpu** [comment] 2021-04-24 01:11
@supermerill Thank you for fixing this! Out of curiosity, what was the issue?

**Comment by supermerill** [comment] 2021-04-25 23:07
I compared first.distance_to( first) instead of last.ditance_to(first)

**Comment by CCS86** [comment] 2021-06-15 02:40
I still seem to be seeing some of this effect on  2.3.56.5:

![image](https://user-images.githubusercontent.com/12439543/121984576-d3d99400-cd58-11eb-9ccf-551445e152c2.png)



2.2.53:

![image](https://user-images.githubusercontent.com/12439543/121984610-e6ec6400-cd58-11eb-83ec-4f76a2a311ef.png)



It seems that 2.2.53 has much better small radii, but worse flat wall precision. But both have defects on both types of surface.

[Edging Coupler 90.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6652398/Edging.Coupler.90.3mf.txt)

**Comment by supermerill** [comment] 2021-06-15 09:49
@CCS86 the "no perimter on bridge area" is the problem. Will be fixed in next release.

**Comment by CCS86** [comment] 2021-06-15 13:40
> @CCS86 the "no perimeter on bridge area" is the problem. Will be fixed in next release.
> also you have a very high "printer-> min extrusion size"



I used to run that setting at 0.005mm, but when you updated the behavior, I found that 0.25mm gave equivalent number of print segments to the prior 0.005mm setting. Perhaps the overly dense gap fill in the newer version skewed this comparison a bit. 

Setting down to 0.05mm still shows the issue though:

![image](https://user-images.githubusercontent.com/12439543/122062759-5001c500-cdb5-11eb-9e5c-ca1034d72c3c.png)

**Comment by supermerill** [comment] 2021-06-15 13:48
> Setting down to 0.05mm still shows the issue though:

I may repeat myself a bit but:

> the "no perimeter on bridge area" is the problem. Will be fixed in next release.

**Comment by CCS86** [comment] 2021-06-15 14:41
With "no perimeter on bridge areas" = remove perimeters:


![image](https://user-images.githubusercontent.com/12439543/122072907-9bb86c80-cdbd-11eb-8a04-d5195038aa49.png)



With "no perimeter on bridge areas" = disabled:


![image](https://user-images.githubusercontent.com/12439543/122072960-aa068880-cdbd-11eb-9675-16366f50dce3.png)




It looks better, but still not fully consistent in stacking the print segments. Min extrusion length was set to 0.20.

It's also interesting to notice that this setting is somehow changing the extrusion width (look at the top gap fill)

**Comment by CCS86** [comment] 2021-06-15 14:47
With it disabled, you can still see some misalignment on a flat face:

![image](https://user-images.githubusercontent.com/12439543/122074117-90b20c00-cdbe-11eb-9c18-311aa2650917.png)


(also present with min extrusion length = 0)

**Comment by supermerill** [comment] 2021-06-15 20:21
with 0.05 min extr dist

![image](https://user-images.githubusercontent.com/6536403/122118049-e79ffb80-ce27-11eb-92f3-6cd586b66880.png)

There is still some misalignment on a flat face, like you say. I'll see where it comes.

**Comment by supermerill** [comment] 2021-06-15 21:19
found the culprit: the curve_smooting is activated and is trying to smoothen some layers but not all of them... for whatever reason. Have to rewrite it.

**Comment by CCS86** [comment] 2021-06-15 23:54
Good catch! 

I hadn't used that feature in the past, but recently made a print where there was a very large radius curve. It came out with a noticeably faceted appearance. Once I tuned the curve smooth settings, it did a great job at shrinking those facets until they were not visible.

I never would have guessed that it was causing the flat face issue. 

Sorry to add to your backlog!

**Comment by CCS86** [comment] 2021-06-26 15:54
Hey @supermerill I just tested in 2.3.56.6 and it appears the "curve smoothing" disrupting flat faces bug is still present.

**Comment by supermerill** [comment] 2021-06-26 17:16
> Hey @supermerill I just tested in 2.3.56.6 and it appears the "curve smoothing" disrupting flat faces bug is still present.

extremely important: use a loose resolution setting, and hight model rounding precision, something like 0.02mm and 0.001). the whole point of the feature is to make nice curve on low-polygon model, so you must be sure it's as simple as possible.
Be sure your cutoff is good.

Also I can't know if a flat surface needs to be curved or not, so it will always be some mishap, that's inevitable.

**Comment by CCS86** [comment] 2021-06-27 02:56
Resolution=0.02
Rounding Precision=0.001

![image](https://user-images.githubusercontent.com/12439543/123531286-efce2580-d6c8-11eb-844f-927c08c1c9bf.png)




Resolution=0
Rounding Precision=0.00001

![image](https://user-images.githubusercontent.com/12439543/123531295-fceb1480-d6c8-11eb-9fae-87a407214e51.png)


I think the second one looks slightly better.

But keep those settings and change 'curve smoothing precision' from 1.6mm to 0mm... perfect:

![image](https://user-images.githubusercontent.com/12439543/123531331-46d3fa80-d6c9-11eb-9feb-e085656ac6f7.png)

**Closed** 2021-07-10 17:02 UTC
Labels: bug, fix is live in the last release
