### ISSUE TITLE
Feature Request: Z-Lift Only on Top Layers

### ISSUE THREAD

**Issue by Matts-Hub** [supermerill/SuperSlicer#607] opened 2020-10-28 01:16 UTC
With particularly stringy filaments, z lift makes the stringing even worse. I only use z-lift to stop scarring on top solid infill from the nozzle dragging across. For these reasons, it would be great if there was a tick box similar to what we already have for z lift "not on top", except this new feature would be "only on top"

**Comment by supermerill** [comment] 2020-10-28 09:41
duplicate of #395, please use the other issue for commenting.

**Closed by supermerill** 2020-10-28 09:41 UTC
