### ISSUE TITLE
Time estimate and Filament use inconcistencies

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#515] opened 2020-10-01 11:36 UTC
Latest version
- Filament usage calculations wrong
- Time estimate (buffer overun? un/signed error?

![image](https://user-images.githubusercontent.com/958490/94804077-898ecd80-03ea-11eb-9cda-530030b3a964.png)

**Comment by thierryzoller** [comment] 2020-10-01 11:39
This is happening repeatably after a few days of use. If I restart the error disappears. Sound like a memory managementerror ?

[usedfilament.zip](https://github.com/supermerill/SuperSlicer/files/5311633/usedfilament.zip)

**Comment by supermerill** [comment] 2020-10-01 12:18
duplicate of #364

**Comment by thierryzoller** [comment] 2020-10-01 18:25
I have good news for you, the -24xxxxxx is reproducible. Just open the file. I mistakenly did a 0.1 multiplier, wich results in these filament usage calcs. However the time should still not be zero. Can you try opening the file?

**Comment by supermerill** [comment] 2020-10-01 19:19
![Uploading image.png…]()

**Comment by thierryzoller** [comment] 2020-10-01 22:08
Interesting, would a memory dump help you find the cause?

**Comment by supermerill** [comment] 2020-10-01 23:03
not unless you put a breakpoint where the problem lie (and i don't know where it is).

**Comment by ManIkWeet** [comment] 2020-10-02 16:46
I too ran into this, curious indeed.
Maybe my file will allow you to reproduce the issue?

[negative time.zip](https://github.com/supermerill/SuperSlicer/files/5319268/negative.time.zip)

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate
