### ISSUE TITLE
Modifier (cylinder) sparse infill speed setting not working.

### ISSUE THREAD

**Issue by SchoGiGIT** [supermerill/SuperSlicer#3849] opened 2023-05-16 14:58 UTC
### What happened?

Created modifier part overlapping with my part. (cyclinder in center of part, look at slower speeds)
Added multiple speed modiferes to this part.
All modifiers seem to work except sparse infill speed (see both standard 180mm/s) even though it is set at 80mm/s

![image](https://github.com/supermerill/SuperSlicer/assets/125773170/bf04ea49-6711-410b-b673-2a1225ad3861)

![image](https://github.com/supermerill/SuperSlicer/assets/125773170/87e1c56e-e5f8-4652-aa87-a85e7d5c3fd4)

### Project file & How to reproduce

[Squad_dome7_cylinder.zip](https://github.com/supermerill/SuperSlicer/files/11489163/Squad_dome7_cylinder.zip)

### Version

2.5.59

### Operating system

Windows 10

### Printer model

Ratrig vCore3-500

**Comment by ft276** [comment] 2024-01-01 09:43
I am still having this issue unfortunately.

I have a workaround.
If you change the sparse infill line thickness in the modifier, as well as the speed, this corrects the issue.
The thickness can be changed from e.g. 0.5 to 0.51 and it will produce the correct speed. You cannot keep the thickness exactly the same as the default with just the 'modifier' tag on however.

**Comment by supermerill** [comment] 2024-01-16 10:28
Thanks for the heads-up.

It's kinda an undocumented feature.
The most likely root cause is:
 . fill regions are merged to prevent artificial frontier between them, unless a useful setting is changed.
 . infill_speed isn't listed as useful setting for creating infill
these speed are available for modifiers to be used with layer range modifier only.
I will make infill_speed/solid_speed/top_speed as settings that will split fill areas, i guess it's the most sane way to do it.

One day, I won't need to split fill & perimeter anymore for speed to be changed... not a easy task though.

**Comment by ft276** [comment] 2024-01-16 12:26
Thank you. It's a shame about having to create perimeters between regions like this as it is likely to compromise strength but sounds like not an easy fix. But, this change will stop me from having to set infill speed slow for the entire model, to allow it to be slow for the overhangs. 
Much appreciated.
What would be really good is to have the option of more than one height modifier, as given the perimeter limitations I find myself having to use large box modifiers that cover entire layers in order to change speed settings for a section, and that would be much easier with extra height modifiers. 
Perhaps I'll make a feature request for that. 

Anyway, much appreciated.

**Comment by supermerill** [comment] 2024-01-16 16:02
You have to be on the "Layers" label in the right panel, no the individual one.

**Closed** 2024-02-14 21:19 UTC
Labels: bug, fix is live in the last release
