### ISSUE TITLE
Wrong print settings profile name for 0.08mm HIGHDETAIL

### ISSUE THREAD

**Issue by fraaancooo** [supermerill/SuperSlicer#1104] opened 2021-04-24 00:14 UTC
### Version
_Version 2.3.55_

### Operating system type + version
_Windows 10 Home, 21H1, OS Compilation 19043.962, Windows Feature Experience Pack 120.2212.3530.0_

### Behavior
* _Wrong print settings profile name. "**0.8mm** HIGHDETAIL" should be "**0.08mm** HIGHDETAIL". That's it!_

![image](https://user-images.githubusercontent.com/18744193/115940386-c3ebb500-a477-11eb-80c9-3589dfb45847.png)

**Comment by Pavulon87** [comment] 2021-04-24 06:24
Duplicate of #1060

**Comment by supermerill** [comment] 2021-04-25 01:18
When the configs has been moved into their own repo, the fix hasn't been used. Fixed since a week.

**Closed** 2021-06-04 16:47 UTC
Labels: fix is live in the last release
