### ISSUE TITLE
First layer infill differs from next layers along Z axis

### ISSUE THREAD

**Issue by inovatorius** [supermerill/SuperSlicer#4145] opened 2024-02-22 00:20 UTC
### What happened?

First layer infill:
![image](https://github.com/supermerill/SuperSlicer/assets/122360472/c37a179d-8434-4d53-b932-295c0cfd03a6)

The next layers:
![image](https://github.com/supermerill/SuperSlicer/assets/122360472/fee05a6f-0eb0-492f-bc06-ab440319770f)

As if first layer has different infill percentage then the other layers.

### Project file & How to reproduce

[Shape-Cylinder.zip](https://github.com/supermerill/SuperSlicer/files/14366493/Shape-Cylinder.zip)

**Comment by supermerill** [comment] 2024-02-23 10:21
because of extrusion width
It ensure it has the good coverage for the current extrusion width, and that shift everything.

I can add a setting to make it "aligned", (so it will make the infiil% wrong but for one extrusion width)

**Comment by supermerill** [comment] 2024-02-28 15:46
duplicate of #4131

**Closed by supermerill** 2024-02-28 15:46 UTC
Labels: new Feature
