### ISSUE TITLE
Letters on top of flat surface produces artifacts in the top layer of the flat surface

### ISSUE THREAD

**Issue by cnrd** [supermerill/SuperSlicer#1221] opened 2021-06-01 17:18 UTC
### Version
2.3.56.1

### Operating system type + version
macOS 10.15.6

### Behavior
Problem:
When slicing my model, SuperSlicer creates small artifacts on the layer below the layer where the letters begin
![Screenshot 2021-06-01 at 19 12 40](https://user-images.githubusercontent.com/5996053/120364331-6a479780-c30d-11eb-9f76-c23d67a5705d.png)
![Screenshot 2021-06-01 at 19 12 48](https://user-images.githubusercontent.com/5996053/120364743-e3df8580-c30d-11eb-910e-87e4529d9cac.png)

Slicing the exact same model in PrusaSlicer produces no such artifacts:
![Screenshot 2021-06-01 at 19 14 08](https://user-images.githubusercontent.com/5996053/120364450-8ba88380-c30d-11eb-802f-baee246ec80f.png)
![Screenshot 2021-06-01 at 19 16 21](https://user-images.githubusercontent.com/5996053/120364754-e641df80-c30d-11eb-82fc-4156c399968a.png)

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
[model.zip](https://github.com/supermerill/SuperSlicer/files/6578263/model.zip)
Includes both the 3MF and stl file

**Comment by supermerill** [comment] 2021-06-01 17:24
duplicate of #1138
the 1peri  min width to 0
or use a modifier layer range

**Closed by supermerill** 2021-06-01 17:24 UTC
Labels: duplicate
