### ISSUE TITLE
UI Graphical issues

### ISSUE THREAD

**Issue by superblobmonster** [supermerill/SuperSlicer#2498] opened 2022-03-09 04:41 UTC
### Version
Screenshots are all from 2.3.57.11, also happens in 2.4.58.1

### Operating system type + version

![image](https://user-images.githubusercontent.com/7859989/157370906-10c42ebc-cebe-441e-bc9e-02eaa72664a4.png)
![image](https://user-images.githubusercontent.com/7859989/157372912-237f124b-10ec-48eb-a2c7-8c0b8544237b.png)
* GUI Settings:
![image](https://user-images.githubusercontent.com/7859989/157372724-7e50db4e-729f-499c-8ab5-ff31ace596e5.png)

### Behavior
A majority of the non-resizable windows have cropped content and inaccessible options.
Some of the normal slicer options have text boxes that are too small, strange text wrapping, and partially cropped buttons.
![image](https://user-images.githubusercontent.com/7859989/157371004-d2713c9d-fbc7-4434-993b-da3e7577544f.png)
![image](https://user-images.githubusercontent.com/7859989/157373216-1c34910d-2b19-4ff6-b6b3-37af60722fe3.png)
![image](https://user-images.githubusercontent.com/7859989/157373626-744ea3a0-a9fc-464a-8756-1fc38dc09ff2.png)
![image](https://user-images.githubusercontent.com/7859989/157372657-581bccae-9225-4a6c-90dd-2de1edcd1ff4.png)

**Comment by supermerill** [comment] 2022-03-09 11:16
maybe related: #1054 #1698

**Comment by supermerill** [comment] 2022-03-14 11:01
gtk2: checkboxes are too small
gtk3: +- on int types are messing everything as they are huge.

I'll remove the +- on gtk3, to avoid problems (I don't have the weeks needed to ensure all the GUI is handling these widget perfectly)
I'll see if I can do something for the checkboxes on gtk2

**Comment by neophyl** [comment] 2022-03-14 13:19
I recall that PS had all sorts of issues around this area too and they are now only supporting their specific app images, so an issue needs to be applicable to those rather than anything self compiled.
Not sure if they are using specific versions of gtk2/3 that have any modifications.  

Not really up on Linux but do tend to monitor the PS github :)

**Comment by supermerill** [comment] 2022-03-14 15:20
Found a fix for gtk2, using toggle buttons instead of checkbox (when the zoom is too high).

**Comment by supermerill** [comment] 2022-03-14 16:06
for gtk3, I just increased a bit the size of the widget.
Will be in next nightly, please report.

**Comment by superblobmonster** [comment] 2022-03-15 13:17
I don't see a nightly for Linux yet, will test when appimage is available

**Comment by supermerill** [comment] 2022-03-16 10:57
sorry, one fix doesn't compile on linux. And it's much more tricky to make it compile as intended.

**Comment by superblobmonster** [comment] 2022-03-25 15:19
Fixed in Nigthly ubuntu #522

**Closed** 2022-07-14 14:44 UTC
Labels: bug, also in prusaslicer, fix is live in the last release
