### ISSUE TITLE
Changing the part size changes the part position

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#938] opened 2021-02-02 17:14 UTC
### Versions

- 2.3.55.2
- 2.3.55.4

### Operating system type + version
Windows 10, 10.0.19042 Build 19042

### Behavior
Changing the part size in X, Y or both XY changes the X, Y or both XY position

### Steps to reproduce
1. Generate a calibrating cube (or load a file)
2. Change the part size in X, Y or both XY
3. See the position change

**Expected behavior**
Changing the part size doesn't changes the part position relative to the center of the part

**Actual behavior**
Changing the part size changes the XY position

**Screenshots**

Base line
![bandicam 2021-02-02 17-59-34-864](https://user-images.githubusercontent.com/57561110/106636018-c7ab2200-6581-11eb-9374-488dcb3c4196.jpg)

XY 50%
![bandicam 2021-02-02 17-59-46-669](https://user-images.githubusercontent.com/57561110/106636093-dabdf200-6581-11eb-8992-0f673cf97851.jpg)

XY 150%
![bandicam 2021-02-02 17-59-50-541](https://user-images.githubusercontent.com/57561110/106636116-e1e50000-6581-11eb-8e43-328d05e883ca.jpg)

X 50%, Y 100%
![bandicam 2021-02-02 18-00-07-584](https://user-images.githubusercontent.com/57561110/106636159-ef01ef00-6581-11eb-8a1d-6366bfe890c3.jpg)

X 150%, Y 100%
![bandicam 2021-02-02 18-01-25-221](https://user-images.githubusercontent.com/57561110/106636210-fd500b00-6581-11eb-8d29-61ebe73f0b61.jpg)

X 100%, Y 50%
![bandicam 2021-02-02 18-01-41-448](https://user-images.githubusercontent.com/57561110/106636246-06d97300-6582-11eb-922c-2575cf81450d.jpg)

X 100%, Y 150%
![bandicam 2021-02-02 18-00-32-618](https://user-images.githubusercontent.com/57561110/106636270-0ccf5400-6582-11eb-829c-c5f198806ade.jpg)

#### Project File (.3MF) where problem occurs

[xyzCalibration_cube-3mf.zip](https://github.com/supermerill/SuperSlicer/files/5912947/xyzCalibration_cube-3mf.zip)

**Comment by supermerill** [comment] 2021-03-19 11:00
I think I change the wrong value when I'm moving objects in the calibration code because I can't reproduce that with a "Add Shape->cube", and the calibration position creates some issues.

So it will fixed with #975.

**Closed** 2021-06-04 16:51 UTC
Labels: duplicate, problem
