### ISSUE TITLE
Coordinate outside allowed range

### ISSUE THREAD

**Issue by wesk-ms** [supermerill/SuperSlicer#1891] opened 2021-11-16 02:19 UTC
New bug for same issue reported recently in issue #66

**Describe the bug**

Import any STL file
Move the part to a different part of the bed (move it enough that the new location isn't overlapping where it was originally).
Configure the part to be printed with a brim.
Slice as usual.

During the slicing operation, I receive a dialog box that says "Coordinate outside allowed range"

**Expected behavior**

Slicing operation should complete without error

**Screenshots**

![image](https://user-images.githubusercontent.com/22187153/141883740-2dc02907-6f61-4506-9656-11fc71de4137.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - SuperSlicer Version:  2.3.57.5

**Additional context**

The STL slices correctly if it isn't moved after being imported.

**Comment by supermerill** [comment] 2021-11-16 15:00
seems like a duplicate of #66

**Comment by wesk-ms** [comment] 2021-11-16 19:09
Issue #66  is very old and seems to include multiple issues that are similar in nature.  I agree that this issue is a duplicate of the most recent problem reported in #66.  However, some of the earlier problems mentioned in #66 don't seem to be related to Brim usage.

I created a new issue to specifically track this error relative to the Brim feature.

**Closed** 2021-12-15 17:51 UTC
Labels: duplicate, fix is live in the last release
