### ISSUE TITLE
Support Lines sliced several times thicker vs Layer Height

### ISSUE THREAD

**Issue by jallen810** [supermerill/SuperSlicer#1628] opened 2021-10-09 22:30 UTC
Basically, the support lines print like the layer height is 3-5x what you set for layer height. I’ve tried different layer heights but doesn’t fix.
This might just be a setting I have goofed but it it happening across 3 computers (2macs and 1 windows) and 3 completely different printers.

here’s the latest gcode
[Left Hand Slide Stop v1_0.12mm_16.3222g_ABS.gcode.txt](https://github.com/supermerill/SuperSlicer/files/7316485/Left.Hand.Slide.Stop.v1_0.12mm_16.3222g_ABS.gcode.txt)

here is what actually printed
![image](https://user-images.githubusercontent.com/62486440/136675053-484bf36c-8e52-4b6f-980e-84592730675d.jpg)

And here is a screens shot of my gcode previewer which is where I caught the support layers looking thicker:
![image](https://user-images.githubusercontent.com/62486440/136675079-3ef08e54-38fe-45a9-83a4-8d762f5d65f8.jpg)

finally here is my .3MF file for this project

[SupportLayerIssue_Left Hand Slide Stop v1.zip](https://github.com/supermerill/SuperSlicer/files/7316491/SupportLayerIssue_Left.Hand.Slide.Stop.v1.zip)

**Comment by supermerill** [comment] 2021-10-09 23:05
duplicate of #1502

**Closed** 2021-10-09 23:05 UTC
Labels: duplicate
