### ISSUE TITLE
Problem bridging when using a sacrificial layer of the same height.

### ISSUE THREAD

**Issue by BoothyBoothy** [supermerill/SuperSlicer#1936] opened 2021-11-20 20:42 UTC
### Version
SuperSlicer Version 2.3.57

### Operating system type + version
Window 10 64 bit

I am relatively new to super slicer but cannot find anything online regards this so thought It may be worth mentioning it. Apologies if this is just newbie ignorance. This is an awesome slicer!

I use a lot of bridging and sacrificial layers when designing parts to reduce the need for supports.

When slicing with Super Slicer the Bridging retains the adjacent perimeters if a sacrificial layer is set to the same height as the rest of the part making the sacrificial layer useless. If I reduce the sacrificial layer by only 0.1 mm the bridging works fine.

It is logical to design the part with all adjacent layer heights to be the same height. It just complicates things if I have to set my designs to one specific slicer limits when publishing designs.

Is there a work around to this in the settings that I have not noticed?

Apologies again if this is not an issue and just down to my ignorance.

Best wishes Boothy

Bridging with same height sacrificial layers to the holes (0.25 mm layer height)
![ssliver2](https://user-images.githubusercontent.com/62219476/142740324-583d3ac1-4ded-40c6-a46e-63190759a575.jpg)

Bridging with sacrificial layers set to the holes 0.1 mm less than surrounding part @ 0.24 mm layer height.
![ssliver1](https://user-images.githubusercontent.com/62219476/142740326-c41d21ed-42d0-4aca-9808-c7e120b964ad.jpg)

**Comment by supermerill** [comment] 2021-11-20 21:00
duplicate of #1917

also of #1911 #1867

if you want auto-build sacrificial layer, use the nightly.
if you want man-made one, disable "only one peri top" for now, at least on these layers.

**Comment by BoothyBoothy** [comment] 2021-11-20 21:31
Many thanks for a fast response and apologies for my duplication. I will try  your suggestions. Boothy

**Comment by BoothyBoothy** [comment] 2021-11-20 21:56
This work very well, thank you again. Boothy

**Closed** 2021-11-20 21:56 UTC
Labels: duplicate
