### ISSUE TITLE
Crash - Sparse Monotonic 100% infill

### ISSUE THREAD

**Issue by S-ed** [supermerill/SuperSlicer#935] opened 2021-02-02 12:32 UTC
### Version
2.3.55.2

### Operating system type + version
Windows 10 20H2

### 3D printer brand / version + firmware version (if known)
Ender 3 Clone (marlin)

### Behavior
- Open Print Settings -> Infill
- Set Sparse to -> Monotonic
- Set Infill % to 100%
Instant crash

#### Project File (.3MF) where problem occurs
Can crash on an empty project

**Comment by qwewer0** [comment] 2021-02-02 13:57
I too was able to reproduce the issue. (2.3.55.2)

**Comment by qwewer0** [comment] 2021-02-04 22:49
On 2.3.55.4 the slicer is no longer crashes.

**Comment by uepsie** [comment] 2021-02-07 12:11
craches on 2.4.55.4 here too when changing Top layer infill to Monotonic (filled) - non filled and bottom work fine
![image](https://user-images.githubusercontent.com/304272/107146023-d0b33f00-6945-11eb-837a-6cf4003f7ab7.png)

-------

![image](https://user-images.githubusercontent.com/304272/107146032-dc9f0100-6945-11eb-91bd-d0ef29014ad6.png)

**Comment by qwewer0** [comment] 2021-02-07 12:19
@uepsie On 2.3.55.4? It doesn't crashes for me on 2.3.55.4.
And the crash that I experienced on 2.3.55.2 isn't an error message, just the slicer exits without any warning.

As a side note the error from your images are present on 2.3.55.4, but I didn't got it from the monotonic infill.

**Comment by uepsie** [comment] 2021-02-07 14:12
It does crash for me this way as soon as I chose monotonic (filled) for top layer.

**Comment by supermerill** [comment] 2021-03-18 16:36
can't reproduce on 2.3.55.5
Should be fixed

**Closed** 2021-04-27 19:15 UTC
Labels: bug, fix is live in the last release
