### ISSUE TITLE
SuperSlicer New version link goes to wrong place.

### ISSUE THREAD

**Issue by barry99705** [supermerill/SuperSlicer#2989] opened 2022-07-26 12:29 UTC
### What happened?

Opened up superslicer and get the new version available popup at the bottom of the screen.
Click the link and it goes to prusaslicer's page.
<img width="320" alt="Screenshot 2022-07-26 082836" src="https://user-images.githubusercontent.com/1740126/181005873-9f065cda-d53b-4850-85f1-2c95147234ba.png">

### Project file & How to reproduce

Opened up superslicer and get the new version available popup at the bottom of the screen.
Click the link and it goes to prusaslicer's page.

### Version

2.4.58.2

### Operating system

Windows 11

**Comment by supermerill** [comment] 2022-07-26 16:56
duplicate of #2954

**Comment by Stooovie** [comment] 2022-10-30 06:36
Not fixed as of 2.4.58.3. Update tells me there's PrusaSlicer update available, and then opens a PrusaSlicer download page.

**Closed** 2024-02-11 12:48 UTC
Labels: duplicate, fix is live in the last release
