### ISSUE TITLE
Issue: "Only one perimeter on top surfaces" causes artifacts on top slopes

### ISSUE THREAD

**Issue by Czarnyszarf** [supermerill/SuperSlicer#312] opened 2020-06-23 09:26 UTC
### Version
Version: 2.2.51

### Operating system type + version
OS: Windows 10 64bit

### 3D printer brand / version + firmware version (if known)
Printer: Prusa MINI , stock build-in profile with ironing disabled

### Behavior
One perimeter on top causes unnecessary infill on sloping surfaces, it makes "fuzzy" skin on them during printing.  As I see - on each layer it makes "solid infill" winch causes over extrusion.

I attached 3MF file wnich shows you the issue , you can examine it closely :)

Expected results: 1 perimeter only on the very top flat surfaces .

[3MF file showcase of the problem.zip](https://github.com/supermerill/SuperSlicer/files/4818455/3MF.file.showcase.of.the.problem.zip)

One perimeter on top(enabled/disabled) : 
![off](https://user-images.githubusercontent.com/25297827/85386052-5fa05200-b543-11ea-9bcf-84db07b76bec.JPG)
![on](https://user-images.githubusercontent.com/25297827/85386714-38965000-b544-11ea-9b26-8bc2c6ea4b52.JPG)

**Comment by neophyl** [comment] 2020-06-23 16:37
Duplicate of #248 I think.

**Comment by Czarnyszarf** [comment] 2020-06-24 14:59
thanks for the solution!

Tested it and it seems 200-250% is best value for normal 0.4 nozzle

**Comment by supermerill** [comment] 2020-06-24 15:04
ok, i'll change the default value to 200.

**Closed** 2020-08-24 00:03 UTC
Labels: duplicate, fix is live in the last release
