### ISSUE TITLE
bottom_solid_layers and bottom_solid_min_thickness ignored when using height range modifier for the first layer

### ISSUE THREAD

**Issue by tetele** [supermerill/SuperSlicer#1918] opened 2021-11-18 15:46 UTC
**Describe the bug**
The number of bottom layers and min thickness is ignored when you have a height range modifier (altering the infill angle) for less than that min thickness.

**To Reproduce**
1. Create a new project and add an object that's at least 2.5mm in height
2. Set layer height to 0.2mm
3. Set bottom_solid_layers=5 and bottom_solid_min_thickness=0.8mm (I know they don't match, but either one would be useful)
4. Add a height range modifier for height 0-0.2mm and set the fill_angle=90 instead of the default 45
5. Slice the model and notice how, starting from layer #2, the sparse infill is used instead of having another 4 layers of solid bottom infill.

**>> Project File <<**
[rear lid frame.zip](https://github.com/supermerill/SuperSlicer/files/7564032/rear.lid.frame.zip)

**Expected behavior**
I would expect to have the layers affected by the height range modifier, without any interference regarding shell thickness.

**Screenshots**
![ss_angle_1](https://user-images.githubusercontent.com/920098/142448152-319b394b-69b2-4799-a2e8-8c9f8369aa5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.3.57.5

**Additional context**
None

**Comment by supermerill** [comment] 2021-11-18 15:53
duplicate of #258

**Closed** 2021-11-18 16:00 UTC
Labels: duplicate
