### ISSUE TITLE
Feature request: Add time estimate for Klipper PRINT_START macro

### ISSUE THREAD

**Issue by sprior** [supermerill/SuperSlicer#2703] opened 2022-04-14 04:56 UTC
In FLUIDD I notice a time estimate gap between "File" and "Slicer" completion times and would like to get them closer to each other.

I use a PRINT_START in my custom gcode in SS which homes, QGL, warm up, bed leveling, auto_z, probe mesh, and this whole process takes around 10 minutes to complete, but it occurs to me that SuperSlicer has no way of knowing how long that one line of gcode might take so it doesn't account for it in the print time estimate.

I'm wondering if there is or could be a way to provide to SS an estimated time cost for a given line of gcode so SS will be able to create a better time estimate for the entire file?

**Comment by supermerill** [comment] 2022-04-14 09:42
duplicate of #1133

**Closed by supermerill** 2022-04-14 09:42 UTC
