### ISSUE TITLE
W10 Super-Slicer 2.3.56 Gcode Viewer Error 

### ISSUE THREAD

**Issue by 5axes** [supermerill/SuperSlicer#1190] opened 2021-05-27 17:20 UTC
**Describe the bug**
cannot launch the Super-slicer Gcode Viewer on Windows 10 . Get an error message :

**Screenshots**
![image](https://user-images.githubusercontent.com/11015345/119869399-794ed400-bf20-11eb-925a-438f14cdef02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.56.0 & 2.3.56.1

**Comment by supermerill** [comment] 2021-05-27 17:24
duplicate of #1187

**Closed by supermerill** 2021-05-27 17:24 UTC
